### ISSUE TITLE
[Bug] You stumbled upon a bug in vite-plugin-ssr's source code

### ISSUE THREAD

**Issue by SafaAlfulaij** [vikejs/vike#1166]
### Description

This occurs when trying `vite build`:

```
computing gzip size (0)...[vike:buildConfig] [vike@0.4.142][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
✓ built in 2m 12s
error during build:
Error: [vike@0.4.142][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at Object.writeBundle (file:///home/safa/Documents/GitHub/lumofy-lxp-frontend/node_modules/vike/dist/esm/node/plugin/plugins/buildConfig.js:57:17)
    at file:///home/safa/Documents/GitHub/lumofy-lxp-frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24407:40
    at async Promise.all (index 2)
    at PluginDriver.hookParallel (file:///home/safa/Documents/GitHub/lumofy-lxp-frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24335:9)
    at file:///home/safa/Documents/GitHub/lumofy-lxp-frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25690:13
    at catchUnfinishedHookActions (file:///home/safa/Documents/GitHub/lumofy-lxp-frontend/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24770:20)
    at build (file:///home/safa/Documents/GitHub/lumofy-lxp-frontend/node_modules/vite/dist/node/chunks/dep-33545781.js:46405:22)
    at CAC.<anonymous> (file:///home/safa/Documents/GitHub/lumofy-lxp-frontend/node_modules/vite/dist/node/cli.js:812:9)
error Command failed with exit code 1.
```

Assertion details:
```javascript
{ manifestTempFile: '_temp_manifest.json', manifestEntry: undefined }
```

**Comment by brillout** [comment]
Are you using `@vitejs/plugin-legacy`?

**Comment by SafaAlFulaijLumofy** [comment]
> Are you using `@vitejs/plugin-legacy`?

Yes indeed I am:

```javascript
    legacy({
      targets: ["defaults", "not IE 11"],
    }),
```

I also have a custom build where I remove the new imports and keep the legacy:
```javascript

const processStandaloneHtml = () => {
  return {
    name: "standalone-html",
    enforce: "post",
    transformIndexHtml(html) {
      return html
        .replace(/.*script type="module".*/g, "")
        .replace(/script nomodule crossorigin/g, "script")
        .replace(/script nomodule/g, "script");
    },
    generateBundle(options, bundles) {
      for (const fileName in bundles) {
        const chunk = bundles[fileName];

        // Delete normal JS chunks
        if (
          chunk.type === "chunk" &&
          fileName.endsWith(".js") &&
          !fileName.includes("legacy")
        ) {
          delete bundles[fileName];
        }
      }
    },
  };
};
```

**Comment by brillout** [comment]
Closing in favor of https://github.com/vikejs/vike/issues/1154. See workaround until a proper fix lands.
