### ISSUE TITLE
Uncaught (in promise) Error: [vike@0.4.142]

### ISSUE THREAD

**Issue by lvcs** [vikejs/vike#1174]
### Description

Uncaught (in promise) Error: [vike@0.4.142][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at U (chunk-5206dec6.js:1:309)
    at o (chunk-5206dec6.js:2:2569)
    at We (chunk-5206dec6.js:2:6433)
    at Mn (chunk-246c9c58.js:2:15954)
    at it (chunk-246c9c58.js:2:15480)
    at chunk-246c9c58.js:2:18171
    at Array.forEach (<anonymous>)
    at Zn (chunk-246c9c58.js:2:18092)
    at chunk-246c9c58.js:2:12583
    at async r (chunk-246c9c58.js:2:12593)

**Comment by brillout** [comment]
In that call stack trace, which line is the failling assertion? (One of these calls is an `assert()` call: I need that line.)
