### ISSUE TITLE
Aray.forEach error thrown on V1 design 404

### ISSUE THREAD

**Issue by chrisvander** [vikejs/vike#1185]
### Description

Expected my `_error/+Page.tsx` page to show up, instead Vike threw an exception.

```
Error: [vike@0.4.143][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/runtime/renderPage/log404/index.js:81:9
    at Array.forEach (<anonymous>)
    at getPagesAndRoutesInfo (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/runtime/renderPage/log404/index.js:73:18)
    at log404 (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/runtime/renderPage/log404/index.js:18:13)
    at renderPageAlreadyPrepared (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/runtime/renderPage.js:175:11)
    at renderPageAndPrepare (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/runtime/renderPage.js:127:10)
    at file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/runtime/renderPage.js:78:48)
    at file:///Users/chrisvanderloo/Developer/bluefin/bluefin/server/index.ts:3:3653
```

**Comment by luisfloat** [comment]
It appears that this issue might be related to the one I opened (#1183). The symptoms and behavior seem quite similar.

**Comment by brillout** [comment]
I made some changes to that file which I pre-released as `vike@0.4.143-commit-dc6fea`. Do you still get the bug?

**Comment by chrisvander** [comment]
Hmm... having trouble installing your prerelease, stand by

**Comment by chrisvander** [comment]
Right - sorry, a little slow today. Yes that works fine, no error.

**Comment by brillout** [comment]
👍
