### ISSUE TITLE
vue-full-v1: You stumbled upon a bug in Vike's source code

### ISSUE THREAD

**Issue by vivazzi** [vikejs/vike#1188]
### Description

```
17:54:03 [vike@0.4.143][request(1)][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at file:///home/vivazzi/projects/examples/ssr_ssg/vue-full-v1/node_modules/.pnpm/vike@0.4.143_vite@4.5.0/node_modules/vike/dist/esm/shared/route/loadPageRoutes.js:46:25
    at Array.forEach (<anonymous>)
    at getPageRoutes (file:///home/vivazzi/projects/examples/ssr_ssg/vue-full-v1/node_modules/.pnpm/vike@0.4.143_vite@4.5.0/node_modules/vike/dist/esm/shared/route/loadPageRoutes.js:25:14)
    at loadPageRoutes (file:///home/vivazzi/projects/examples/ssr_ssg/vue-full-v1/node_modules/.pnpm/vike@0.4.143_vite@4.5.0/node_modules/vike/dist/esm/shared/route/loadPageRoutes.js:13:24)
    at getRenderContext (file:///home/vivazzi/projects/examples/ssr_ssg/vue-full-v1/node_modules/.pnpm/vike@0.4.143_vite@4.5.0/node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js:151:47)
    at renderPageAndPrepare (file:///home/vivazzi/projects/examples/ssr_ssg/vue-full-v1/node_modules/.pnpm/vike@0.4.143_vite@4.5.0/node_modules/vike/dist/esm/node/runtime/renderPage.js:67:25)
    at file:///home/vivazzi/projects/examples/ssr_ssg/vue-full-v1/node_modules/.pnpm/vike@0.4.143_vite@4.5.0/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///home/vivazzi/projects/examples/ssr_ssg/vue-full-v1/node_modules/.pnpm/vike@0.4.143_vite@4.5.0/node_modules/vike/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///home/vivazzi/projects/examples/ssr_ssg/vue-full-v1/node_modules/.pnpm/vike@0.4.143_vite@4.5.0/node_modules/vike/dist/esm/node/plugin/shared/addSsrMiddleware.js:18:27
17:54:03 [vike][request(1)] HTTP response / ERR
```

I tried to run **vue-full-v1** example with pnpm.

versions:
npm: 9.6.7
node: 18.17.1
pnpm: 8.9.2

**Comment by brillout** [comment]
Does it work `vike@0.4.143-commit-fa295e1` with?

**Comment by brillout** [comment]
I'll re-open if I can get more information on this (or a reproduction).

**Comment by vivazzi** [comment]
I tryied vike=0.4.144 and it helps me. Thank you for awesome vike!
