### ISSUE TITLE
"constructor" search param in URL causes internal server error

### ISSUE THREAD

**Issue by uifox** [vikejs/vike#1205]
### Description

Using vike@0.4.144 I experience a server side error when a search param with key "constructor" is present in the URL, e.g. http://www.example.com/provider/wok?constructor=12

```
TypeError: (searchAll[key] || []) is not iterable
    at file:///home/appuser/node_modules/vike/dist/esm/utils/parseUrl.js:54:46
    at Array.forEach (<anonymous>)
    at parseUrl (file:///home/appuser/node_modules/vike/dist/esm/utils/parseUrl.js:52:59)
    at modifyUrlPathname (file:///home/appuser/node_modules/vike/dist/esm/utils/parseUrl-extras.js:73:72)
    at normalizeUrlPathname (file:///home/appuser/node_modules/vike/dist/esm/utils/parseUrl-extras.js:57:27)
    at normalizeUrl (file:///home/appuser/node_modules/vike/dist/esm/node/runtime/renderPage.js:319:27)
    at renderPageAndPrepare (file:///home/appuser/node_modules/vike/dist/esm/node/runtime/renderPage.js:84:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at file:///home/appuser/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
```

This is caused by https://github.com/vikejs/vike/blob/926313b298dbffac434ab52a44be7b24c1d16d7b/vike/utils/parseUrl.ts#L80

where `searchAll['constructor']` is never `undefined`. It is in fact a function (the constructor of `{}`) causing the `searchAll[key] = [...(searchAll[key] || []), val];` expression to fail.

```
> [...(searchAll['constructor'] || []), 'val'];
Uncaught TypeError: (searchAll.constructor || []) is not iterable
```

**Comment by brillout** [comment]
> @brillout Let me know if I can help fix this issue. I'd be glad to.

Ok!

**Comment by uifox** [comment]
@brillout I cloned this repo, created a branch, fixed this issue, but I can't push my changes. What's the process I should follow?

```
[uifox/issue-1205 afbfceb27] fix: allow "constructor" search param in URL
 2 files changed, 8 insertions(+), 4 deletions(-)
13:23:21.948: [vike] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/uifox/issue-1205:refs/heads/uifox/issue-1205 --set-upstream
ERROR: Permission to vikejs/vike.git denied to uifox.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by brillout** [comment]
See "GitHub forks".
