### ISSUE TITLE
Crash on page render

### ISSUE THREAD

**Issue by jackymayo** [vikejs/vike#1225]
### Description

    at file:///Users/jackyma/Git/ktbyte/earth/earth_dev/web/resources/node_modules/vike/dist/esm/node/runtime/renderPage/log404/index.js:81:9
    at Array.forEach (<anonymous>)
    at getPagesAndRoutesInfo (file:///Users/jackyma/Git/ktbyte/earth/earth_dev/web/resources/node_modules/vike/dist/esm/node/runtime/renderPage/log404/index.js:73:18)
    at log404 (file:///Users/jackyma/Git/ktbyte/earth/earth_dev/web/resources/node_modules/vike/dist/esm/node/runtime/renderPage/log404/index.js:18:13)
    at renderPageAlreadyPrepared (file:///Users/jackyma/Git/ktbyte/earth/earth_dev/web/resources/node_modules/vike/dist/esm/node/runtime/renderPage.js:128:15)
    at renderPageAndPrepare (file:///Users/jackyma/Git/ktbyte/earth/earth_dev/web/resources/node_modules/vike/dist/esm/node/runtime/renderPage.js:93:12)
    at file:///Users/jackyma/Git/ktbyte/earth/earth_dev/web/resources/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///Users/jackyma/Git/ktbyte/earth/earth_dev/web/resources/node_modules/vike/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///Users/jackyma/Git/ktbyte/earth/earth_dev/web/resources/local-dev.js:42:29

**Comment by brillout** [comment]
Does `0.4.144-commit-6aef8a6` fix it?

Closing but I'll re-open if you still get the issue.
