### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by pieperz** [vikejs/vike#1234]
### Description

I was updating some packages/types and ran across this error.

"vite": "4.5.0",
"vite-plugin-ssr": "0.4.142",

 at Object.writeBundle (/Users/james/_Dev/mfqs-vite/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/buildConfig.js:57:39)
    at file:///Users/james/_Dev/mfqs-vite/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
    at async Promise.all (index 2)
    at PluginDriver.hookParallel (file:///Users/james/_Dev/mfqs-vite/node_modules/rollup/dist/es/shared/node-entry.js:25472:9)
    at file:///Users/james/_Dev/mfqs-vite/node_modules/rollup/dist/es/shared/node-entry.js:26792:13
    at catchUnfinishedHookActions (file:///Users/james/_Dev/mfqs-vite/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
    at build (file:///Users/james/_Dev/mfqs-vite/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48085:22)
    at CAC.<anonymous> (file:///Users/james/_Dev/mfqs-vite/node_modules/vite/dist/node/cli.js:842:9)

**Comment by brillout** [comment]
This has already been fixed. Update to latest version `vike@0.4.144`. (The vite-plugin-ssr => Vike migration should be trivial.)

Let me know if you still run into this issue and I'll re-open this ticket.

(Thanks for sponsoring, this makes a big difference 💚)
