### ISSUE TITLE
Issue in Vite Build

### ISSUE THREAD

**Issue by DannyZB** [vikejs/vike#1236]
### Description

error during build:
Error: [vite-plugin-ssr@0.4.142][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at Object.writeBundle (file:///Users/daniel/work/seedr_landing/node_modules/vite-plugin-ssr/dist/esm/node/plugin/plugins/buildConfig.js:54:17)
    at file:///Users/daniel/work/seedr_landing/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
    at async Promise.all (index 2)
    at PluginDriver.hookParallel (file:///Users/daniel/work/seedr_landing/node_modules/rollup/dist/es/shared/node-entry.js:25472:9)
    at file:///Users/daniel/work/seedr_landing/node_modules/rollup/dist/es/shared/node-entry.js:26792:13
    at catchUnfinishedHookActions (file:///Users/daniel/work/seedr_landing/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
    at build (file:///Users/daniel/work/seedr_landing/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48085:22)
    at CAC.<anonymous> (file:///Users/daniel/work/seedr_landing/node_modules/vite/dist/node/cli.js:842:9)

**Comment by brillout** [comment]
Hi Danny, this has already been fixed; update to the latest version.

Let me know if you still get the/an issue then. Closing in the meantime.

**Comment by DannyZB** [comment]
Still getting with version .142

**Comment by brillout** [comment]
The latest version is `vike@0.4.144`. The migration to Vike is fairly straightforward (see migration guide).
