### ISSUE TITLE
React Query v5 dehydratedState is a deeply nested object?

### ISSUE THREAD

**Issue by JoshShearer** [vikejs/vike#1237]
### Description

1:56:03 PM [vike][request(2)] HTTP response /mushrooms/species 200
Error: [vike@0.4.144][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at file:///.../node_modules/vike/dist/esm/node/runtime/html/serializePageContextClientSide.js:49:17
    at Array.forEach (<anonymous>)
    at serializePageContextClientSide (file:///.../node_modules/vike/dist/esm/node/runtime/html/serializePageContextClientSide.js:40:22)
    at getPageContextTag (file:///.../node_modules/vike/dist/esm/node/runtime/html/injectAssets/getHtmlTags.js:127:48)
    at htmlTag (file:///.../node_modules/vike/dist/esm/node/runtime/html/injectAssets/getHtmlTags.js:113:28)
    at resolveHtmlTag (file:///.../node_modules/vike/dist/esm/node/runtime/html/injectAssets/injectHtmlTags.js:54:42)
    at file:///.../node_modules/vike/dist/esm/node/runtime/html/injectAssets/injectHtmlTags.js:13:25
    at Array.map (<anonymous>)
    at file:///.../node_modules/vike/dist/esm/node/runtime/html/injectAssets/injectHtmlTags.js:13:14
    at Array.forEach (<anonymous>)
    at injectHtmlTags (file:///.../node_modules/vike/dist/esm/node/runtime/html/injectAssets/injectHtmlTags.js:10:15)
    at injectToHtmlEnd (file:///.../node_modules/vike/dist/esm/node/runtime/html/injectAssets.js:46:15)
    at injectAtStreamEnd (file:///.../node_modules/vike/dist/esm/node/runtime/html/injectAssets.js:33:19)
    at injectStringAtEnd (file:///.../node_modules/vike/dist/esm/node/runtime/html/renderHtml.js:70:24)
    at onEnd (file:///.../node_modules/vike/dist/esm/node/runtime/html/stream.js:263:39)
    at Writable.destroy [as _destroy] (file:///.../node_modules/vike/dist/esm/node/runtime/html/stream.js:398:21)
Error: [vike@0.4.144][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at onEnd (file:///.../node_modules/vike/dist/esm/node/runtime/html/stream.js:275:21)
    at Writable.destroy [as _destroy] (file:///.../node_modules/vike/dist/esm/node/runtime/html/stream.js:398:21)

**Comment by JoshShearer** [comment]
I see what caused this ...+onRenderHtml return statement incorrect.

```
  return {
    documentHtml,
    pageContext: {
      PRELOADED_STATE,
    },
    // See https://vike.dev/stream#initial-data-after-stream-end
  };
```

**Comment by brillout** [comment]
Seems to be a duplicate of https://github.com/vikejs/vike/issues/1232.

Try `0.4.144-commit-f7ab002` and let me know if you still get the/an issue and I'll re-open.

**Comment by JoshShearer** [comment]
I've tried to install this commit with yarn, as well as npm ....it does not seem to work.   Am I missing something?  

yarn add vike@github:vikejs/vike#f7ab002b1c04dd6ecbc7fcc4e231483dd280e9b8
➤ YN0000: · Yarn 4.0.1
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: vike@https://github.com/vikejs/vike.git#commit=f7ab002b1c04dd6ecbc7fcc4e231483dd280e9b8: Assertion failed: Unsupported workflow
    at /home/joshshearer/.yarn/releases/yarn-4.0.1.cjs:189:1611
    at async Tn.mktempPromise (/home/joshshearer/.yarn/releases/yarn-4.0.1.cjs:9:44852)
    at async /home/joshshearer/.yarn/releases/yarn-4.0.1.cjs:186:56
    at async Tn.mktempPromise (/home/joshshearer/.yarn/releases/yarn-4.0.1.cjs:9:44852)
    at async /home/joshshearer/.yarn/releases/yarn-4.0.1.cjs:181:3026
➤ YN0000: └ Completed in 6s 849ms
➤ YN0000: · Failed with errors in 6s 872ms

**Comment by brillout** [comment]
Set `"vike": "0.4.144-commit-f7ab002"` in your package.json

**Comment by JoshShearer** [comment]
Thank you.  It appears to be working!

**Comment by brillout** [comment]
@JoshShearer Btw. in case your company would be up for it consider [sponsoring](https://github.com/sponsors/brillout) &mdash; it makes a big difference. (Sorry if I told you already before 🙂)
