### ISSUE TITLE
Error during npm build

### ISSUE THREAD

**Issue by briansunter** [vikejs/vike#1287]
### Description

vike v0.4.147 pre-rendering HTML...
Error: [vike@0.4.147][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at addUrlComputedProps (file:///Users/bsunter/code/sitev3/node_modules/.pnpm/vike@0.4.147_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/shared/addUrlComputedProps.js:27:9)
    at route (file:///Users/bsunter/code/sitev3/node_modules/.pnpm/vike@0.4.147_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/shared/route/index.js:18:5)
    at file:///Users/bsunter/code/sitev3/node_modules/.pnpm/vike@0.4.147_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/node/prerender/runPrerender.js:421:44
    at file:///Users/bsunter/code/sitev3/node_modules/.pnpm/vike@0.4.147_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/utils/pLimit.js:30:37
    at run (file:///Users/bsunter/code/sitev3/node_modules/.pnpm/vike@0.4.147_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/utils/pLimit.js:30:49)
    at next (file:///Users/bsunter/code/sitev3/node_modules/.pnpm/vike@0.4.147_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/utils/pLimit.js:24:28)
    at run (file:///Users/bsunter/code/sitev3/node_modules/.pnpm/vike@0.4.147_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/utils/pLimit.js:36:9)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by brillout** [comment]
Are you seting `pageContext.url = '/some/url'`? If you don't then I'll need a reproduction.

**Comment by brillout** [comment]
Closing; I'll re-open if I can get my hands on a reproduction.
