### ISSUE TITLE
Vike crashes on temporary file from IDE

### ISSUE THREAD

**Issue by chrisvander** [vikejs/vike#1298]
### Description

When using my formatter, `conform.nvim`, temp files are created which Vike attempts to consume. I would recommend ignoring files starting with a ".", I imagine other developer tools use the same method to store temporary files.

```
Error: [vike][Wrong Usage] Character '+' is only allowed at the beginning of filenames: make sure /Users/chrisvanderloo/Developer/.../.conform.6589686.+Page.tsx doesn't contain any '+' in its filename other than its first letter
    at assertNoUnexpectedPlusSign (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:860:5)
    at getConfigName (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:844:5)
    at isVikeConfigFile (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:1073:14)
    at listener (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/index.js:70:58)
    at FSWatcher.<anonymous> (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/index.js:65:50)
    at FSWatcher.emit (node:events:526:35)
    at FSWatcher.emit (node:domain:489:12)
    at FSWatcher.emitWithAll (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vite/dist/node/chunks/dep-vyqc0_aB.js:47012:8)
    at FSWatcher._emit (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vite/dist/node/chunks/dep-vyqc0_aB.js:47104:8)
    at FsEventsHandler.handleEvent (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vite/dist/node/chunks/dep-vyqc0_aB.js:46235:14)
    at FsEventsHandler.addOrChange (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vite/dist/node/chunks/dep-vyqc0_aB.js:46185:8)
    at FsEventsHandler.checkExists (file:///Users/chrisvanderloo/Developer/bluefin/bluefin/node_modules/vite/dist/node/chunks/dep-vyqc0_aB.js:46193:12)
```

**Comment by chrisvander** [comment]
That is an excellent point. No, it was not in my `.gitignore`. I added that and haven't ran into the issue again - thanks @brillout!

**Comment by brillout** [comment]
👌 Let me know if there is anything else. Thanks for sponsoring 💚 sponsors are making a massive difference.
