### ISSUE TITLE
Dev server crash when path above Vike root

### ISSUE THREAD

**Issue by DannyZB** [vikejs/vike#1302]
### Description

Hey,

It should return a 404, but instead it crashes the dev server.
The app root is set to "/app" and if I go to localhost:3000 directly it crashes.

10:30:53 AM [vike][request(1)] HTTP request: /

/home/daniel/work/ui_framework/node_modules/vike/dist/cjs/utils/parseUrl-extras.js:28
    (0, assert_js_1.assert)(hasBaseServer);
                           ^
Error: [vike@0.4.142][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at removeBaseServer (/home/daniel/work/ui_framework/node_modules/vike/dist/cjs/utils/parseUrl-extras.js:28:28)
    at getPermanentRedirect (/home/daniel/work/ui_framework/node_modules/vike/dist/cjs/node/runtime/renderPage.js:335:60)
    at renderPageAndPrepare (/home/daniel/work/ui_framework/node_modules/vike/dist/cjs/node/runtime/renderPage.js:95:40)
    at /home/daniel/work/ui_framework/node_modules/vike/dist/cjs/node/plugin/shared/getHttpRequestAsyncStore.js:85:35
    at renderPage (/home/daniel/work/ui_framework/node_modules/vike/dist/cjs/node/runtime/renderPage.js:51:50)
    at /home/daniel/work/ui_framework/vite_server/index.js:31:29

**Comment by brillout** [comment]
Indeed, I could reproduce. Let me fix it.

**Comment by brillout** [comment]
Fix pre-released in `0.4.147-commit-f9a91f3`. (I hope everything is ok with you and your family; I had to think of you because of what is happening in the middle east.)
