### ISSUE TITLE
[Bug] You stumbled upon a bug in Vike's source code. 

### ISSUE THREAD

**Issue by NicoScal** [vikejs/vike#1323]
### Description

I have this error given while I am doing vike v1 library migration

**Comment by NicoScal** [comment]
I have modified all files as described in the migration documentationI have modified all files as described in the migration documentation.

**Comment by brillout** [comment]
I need the *error* stack strack.

**Comment by NicoScal** [comment]
the error:
[Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at assertExports (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/assertExports.js:32:13)
    at assertExportsOfValueFile (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/assertExports.js:14:5)
    at file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/serialize/parseConfigValuesImported.js:24:17
    at Array.forEach (<anonymous>)
    at parseConfigValuesImported (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/serialize/parseConfigValuesImported.js:20:26)
    at loadConfigValues (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/loadConfigValues.js:14:38)
    at loadPageFiles (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage/loadPageFilesServerSide.js:85:51)
    at async Promise.all (index 0)
    at loadPageFilesServerSide (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage/loadPageFilesServerSide.js:13:110)
    at renderPageAlreadyRouted (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js:31:31)
    at renderPageNominal (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage.js:266:36)
    at renderPageAlreadyPrepared (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage.js:121:45)
    at renderPageAndPrepare (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage.js:101:12)
    at file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/server/index.js:69:29.
    
 the index.js file is:
 import express from 'express'
import compression from 'compression'
import {renderPage} from 'vike/server'
import {root} from './root.js'
import {getEpisodesBySeriesSlug, getPage} from "../api.js";
import {APP_HOST} from "../config.js";

const isProduction = process.env.NODE_ENV === 'production';

await startServer();

async function startServer() {
    const app = express()

    app.use(compression())

    // Vite integration
    if (isProduction) {
        // In production, we need to serve our static assets ourselves.
        // (In dev, Vite's middleware serves our static assets.)
        const sirv = (await import('sirv')).default
        app.use(sirv(`${root}/dist/client`))
    } else {
        // We instantiate Vite's development server and integrate its middleware to our server.
        // ⚠️ We instantiate it only in development. (It isn't needed in production and it
        // would unnecessarily bloat our production server.)
        const vite = await import('vite')
        const viteDevMiddleware = (
            await vite.createServer({
                root,
                server: {middlewareMode: true}
            })
        ).middlewares
        app.use(viteDevMiddleware)
    }

    app.get('/:pageSlug/episodes/:seriesSlug/feed', async (req, res, next) => {
        const {pageSlug, seriesSlug} = req.params;
        const {onDemandServiceId} = await getPage(pageSlug)
        const feed = await getEpisodesBySeriesSlug(seriesSlug, onDemandServiceId, {
            permalinkBase: APP_HOST + '/' + pageSlug,
            type: 'rss',
            limit: 1000
        });
        res.set('Content-Type', 'text/xml')
        res.send(feed)
    });

    // Vike middleware. It should always be our last middleware (because it's a
    // catch-all middleware superseding any middleware placed after it).
    app.get('*', async (req, res, next) => {
        const pageContextInit = {
            urlOriginal: req.originalUrl,
            acceptsLanguages: req.acceptsLanguages()
        }
// the error is in this row
        const pageContext = await renderPage(pageContextInit)
        const {httpResponse} = pageContext
        if (!httpResponse) {
            return next()
        } else {
            const {body, statusCode, headers, earlyHints} = httpResponse
            if (res.writeEarlyHints) res.writeEarlyHints({link: earlyHints.map((e) => e.earlyHintLink)})
            headers.forEach(([name, value]) => res.setHeader(name, value))
            res.status(statusCode)
            // For HTTP streams use httpResponse.pipe() instead, see https://vike.dev/stream
            res.send(body)
        }
    })

    const port = process.env.PORT || 3123
    app.listen(port)
    console.log(`Server running at http://localhost:${port}`)
}

**Comment by brillout** [comment]
I see what's going, let me fix it and release the fix.

**Comment by NicoScal** [comment]
ok tell me when the fix will be released

**Comment by NicoScal** [comment]
the problem has been solved.
Now I have another problem in file /pages/profile/+onBeforeRender.js:

`import {getPage, getSeries} from "../../api.js";
import {redirect, render} from "vike/abort";

async function onBeforeRender(pageContext) {
    // throw redirect('/radiotaormina', 301)
    const { pageSlug } = pageContext.routeParams;

    const pageResult = await getPage(pageSlug)

    if (!pageResult) {
        throw render(404, `${pageSlug} doesn't exist.`)
    }

    let onDemandServiceId = pageResult.onDemandServiceId;

    if (!onDemandServiceId) {
        throw new Error('Failed to fetch on-demand service')
    }

    let onDemandSeries = await getSeries(onDemandServiceId);

    // console.log(onDemandSeries)

    const pageProps = {
        page: pageResult,
        onDemandSeries,
        routeParams: pageContext.routeParams
    };

    // We make `pageProps` available as `pageContext.pageProps`
    return {
        pageContext: {
            pageProps
        }
    };
}

// By default, `pageContext` is available only on the server. But our hydrate function
// we defined earlier runs in the browser and needs `pageContext.pageProps`; we use
// `passToClient` to tell `vvike` to serialize and make `pageContext.pageProps`
// available to the browser.
export default{
    onBeforeRender,
    passToClient: ['pageProps', 'documentProps']
}`
the error is: "[Wrong Usage] Hook onBeforeRender() defined by /pages/profile/+onBeforeRender.js should be a function"

**Comment by brillout** [comment]
Follow the migration guide.

**Comment by NicoScal** [comment]
I have another error given while I am doing vike v1 library migration.
`[Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at assertExports (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/assertExports.js:32:13)
    at assertExportsOfValueFile (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/assertExports.js:14:5)
    at file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/serialize/parseConfigValuesImported.js:24:17
    at Array.forEach (<anonymous>)
    at parseConfigValuesImported (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/serialize/parseConfigValuesImported.js:20:26)
    at loadConfigValues (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/shared/page-configs/loadConfigValues.js:14:38)
    at loadPageFiles (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage/loadPageFilesServerSide.js:85:51)
    at async Promise.all (index 0)
    at loadPageFilesServerSide (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage/loadPageFilesServerSide.js:13:110)
    at renderPageAlreadyRouted (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js:31:31)
    at renderPageNominal (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage.js:266:36)
    at renderPageAlreadyPrepared (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage.js:121:45)
    at renderPageAndPrepare (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage.js:101:12)
    at file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/node_modules/vike/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///C:/Users/n.scaletti/WebstormProjects/xsocial-inonda-webapp/server/index.js:81:29
`.
file index.js is:
`// This file isn't processed by Vite, see https://github.com/vikejs/vike/issues/562
// Consequently:
//  - When changing this file, you needed to manually restart your server for your changes to take effect.
//  - To use your environment variables defined in your .env files, you need to install dotenv, see https://vite-plugin-ssr.com/env
//  - To use your path aliases defined in your vite.config.js, you need to tell Node.js about them, see https://vite-plugin-ssr.com/path-aliases

// If you want Vite to process your server code then use one of these:
//  - vavite (https://github.com/cyco130/vavite)
//     - See vavite + vite-pugin-ssr examples at https://github.com/cyco130/vavite/tree/main/examples
//  - vite-node (https://github.com/antfu/vite-node)
//  - HatTip (https://github.com/hattipjs/hattip)
//    - You can use Bati (https://batijs.github.io/) to scaffold a vike + HatTip app. Note that Bati generates apps that use the V1 design (https://vite-plugin-ssr.com/migration/v1-design) and Vike packages (https://vite-plugin-ssr.com/vike-packages)

import express from 'express'
import compression from 'compression'
import {renderPage} from 'vike/server'
import {root} from './root.js'
import {getEpisodesBySeriesSlug, getPage} from "../api.js";
import {APP_HOST} from "../config.js";

const isProduction = process.env.NODE_ENV === 'production';

await startServer();

async function startServer() {
    const app = express()

    app.use(compression())

    // Vite integration
    if (isProduction) {
        // In production, we need to serve our static assets ourselves.
        // (In dev, Vite's middleware serves our static assets.)
        const sirv = (await import('sirv')).default
        app.use(sirv(`${root}/dist/client`))
    } else {
        // We instantiate Vite's development server and integrate its middleware to our server.
        // ⚠️ We instantiate it only in development. (It isn't needed in production and it
        // would unnecessarily bloat our production server.)
        const vite = await import('vite')
        const viteDevMiddleware = (
            await vite.createServer({
                root,
                server: {middlewareMode: true}
            })
        ).middlewares
        app.use(viteDevMiddleware)
    }

    app.get('/:pageSlug/episodes/:seriesSlug/feed', async (req, res, next) => {
        const {pageSlug, seriesSlug} = req.params;
        const {onDemandServiceId} = await getPage(pageSlug)
        const feed = await getEpisodesBySeriesSlug(seriesSlug, onDemandServiceId, {
            permalinkBase: APP_HOST + '/' + pageSlug,
            type: 'rss',
            limit: 1000
        });
        res.set('Content-Type', 'text/xml')
        res.send(feed)
    });

    // Vike middleware. It should always be our last middleware (because it's a
    // catch-all middleware superseding any middleware placed after it).
    app.get('*', async (req, res, next) => {
        const language =  req.acceptsLanguages()
        if(language[0].startsWith('it')){
            language[0] = 'it'
        }
        if(language[0].startsWith('en')){
            language[0] = 'en'
        }

        if(!language[0].startsWith('it') && !language[0].startsWith('en')){
            language[0] = 'en'
        }
        const pageContextInit = {
            urlOriginal: req.originalUrl,
            acceptsLanguages: req.acceptsLanguages(),
            locale: language[0]
        }
        const pageContext = await renderPage(pageContextInit)
        const {httpResponse} = pageContext
        if (!httpResponse) {
            return next()
        } else {
            const {body, statusCode, headers, earlyHints} = httpResponse
            if (res.writeEarlyHints) res.writeEarlyHints({link: earlyHints.map((e) => e.earlyHintLink)})
            headers.forEach(([name, value]) => res.setHeader(name, value))
            res.status(statusCode)
            // For HTTP streams use httpResponse.pipe() instead, see https://vike.dev/stream
            res.send(body)
        }
    })

    const port = process.env.PORT || 3123
    app.listen(port)
    console.log(`Server running at http://localhost:${port}`)
}
`
http repsponse is "HTTP response /radiotaormina/episodes/la-serie-di-nicolo 500
".
Could you tell me which file the problem might be in?

**Comment by NicoScal** [comment]
The problem has been solved. thanks
