### ISSUE TITLE
"Invalid state: Controller is already closed" on a small portion of requests

### ISSUE THREAD

**Issue by jakubfiala** [vikejs/vike#1325]
### Description

We've been seeing errors thrown by the Node `ReadableStream` Controller on a small percentage of requests in production. These seem to be coming from Vike's streaming code. We suspect it could be to do with handling dropped requests.

Here's the stack trace:

```
TypeError: Invalid state: Controller is already closed
  File "node:internal/errors", line 405, col 5, in new NodeError
  File "node:internal/webstreams/readablestream", line 1038, col 13, in ReadableStreamDefaultController.enqueue
  File "/src/node_modules/vike/dist/esm/node/runtime/html/stream.js", line 512, col 29, in Object.writeChunk
    controllerProxy.enqueue(encodeForWebStream(chunk));
  File "/src/node_modules/vike/dist/esm/node/runtime/html/stream.js", line 297, col 37, in <anonymous>
    streamWrapperOperations.writeChunk(chunk);
  File "<anonymous>", in Array.forEach
  File "/src/node_modules/vike/dist/esm/node/runtime/html/stream.js", line 296, col 16, in flushBuffer
    buffer.forEach((chunk) => {
  File "/src/node_modules/vike/dist/esm/node/runtime/html/stream.js", line 291, col 9, in writeStream
    flushBuffer();
  File "/src/node_modules/vike/dist/esm/node/runtime/html/stream.js", line 251, col 13, in onData
    writeStream(chunk);
  File "/src/node_modules/vike/dist/esm/node/runtime/html/stream.js", line 578, col 9, in handleReadableWeb
    onData(value);
  File "node:internal/process/task_queues", line 95, col 5, in process.processTicksAndRejections
```

and here's how we send the stream from Vike (using Fastify):

```js
  const { errorWhileRendering, httpResponse: page } = await renderPage(context);

  if (!page) {
    throw new Error(errorWhileRendering);
  }

  reply.writeEarlyHints(getEarlyHintsLinks(page.earlyHints));
  // Vike gives us a Web stream, but Fastify expects us to give it a Node.js stream
  const stream = Readable.fromWeb(page.getReadableWebStream());

  return reply
    .headers(Object.fromEntries(page.headers))
    .status(page.statusCode)
    .send(stream);
```

Happy to provide more info if needed. This only seems to be happening on less than 1% of requests.

**Comment by jakubfiala** [comment]
@brillout thanks! So we're using Fastify for our server, and the way it supports streams, is that in your handler (`(request, reply, next) => {}`) you call `reply.send(myStream)`. It doesn't support piping.

I can obtain the raw Node `Response` object from the Fastify `reply`, but when I try to pipe to that, I get:

```
[09:29:52.183] ERROR:
    message: "[vike@0.4.147]\u001b[1m\u001b[31m[Bug]\u001b[39m\u001b[22m You stumbled upon a bug in Vike's source code. Go to \u001b[34mhttps://github.com/vikejs/vike/issues/new\u001b[39m and copy-paste this error; a maintainer will fix the bug (usually under 24 hours)."
    err: {
      "type": "Error",
      "message": "[vike@0.4.147]\u001b[1m\u001b[31m[Bug]\u001b[39m\u001b[22m You stumbled upon a bug in Vike's source code. Go to \u001b[34mhttps://github.com/vikejs/vike/issues/new\u001b[39m and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).",
      "stack":
          Error: [vike@0.4.147][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
              at Object.pipe (file:///Users/jakub.f/code/ecosia/core/node_modules/vike/dist/esm/node/runtime/renderPage/getHttpResponseBody.js:84:21)
              at IncomingMessage.render (file:///Users/jakub.f/code/ecosia/core/taproot/fastify-plugin/render.js:26:8)
              at Object.get (file:///Users/jakub.f/code/ecosia/core/search/images-taproot/src/server/handlers.js:135:7)
    }
```

**Comment by jakubfiala** [comment]
@brillout alrighty, thanks for the fix! That sentence from me was worded weirdly - I didn't mean "your" as in Vike's, I meant "you as a developer using Fastify" :D

Good to know re: piping. Sadly we can't use it until Fastify gives us an interfacte to do so. But with the `readable.cancel()` fix at least the Invalid state issue is mitigated, thanks a lot!

**Comment by jakubfiala** [comment]
@brillout the errors have stopped occurring after updating to `0.4.150` - thank you for the quick fix!

**Comment by brillout** [comment]
@jakubfiala Thanks Jakub. I'm glad it's fixed and it's good to know as I was shooting in the dark without repro :)
