### ISSUE TITLE
vike-react/ClientOnly

### ISSUE THREAD

**Issue by SMKJALLAD** [vikejs/vike#1328]
### Description

PS C:\Users\suhai\OneDrive\Documents\GitHub\SkyvertiseVike> npx vite --port=4000
11:53:57 AM [vike@0.4.149][config][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours). Debug info (for Vike maintainers; you can ignore this): Not a posix path: (empty string)
    at assertPosixPath (file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/utils/filesystemPathHandling.js:13:5)
    at toPosixPath (file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/utils/filesystemPathHandling.js:6:5)
    at file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/crawlPlusFiles.js:40:13
    at Array.map (<anonymous>)
    at crawlPlusFiles (file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/crawlPlusFiles.js:39:29)
    at findPlusFiles (file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:798:19)
    at loadInterfaceFiles (file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:73:23)
    at loadVikeConfig (file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:233:40)
    at loadVikeConfig_withErrorHandling (file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:196:15)
    at getVikeConfig (file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:70:12)
    at getConfigVikPromise (file:///C:/Users/suhai/OneDrive/Documents/GitHub/SkyvertiseVike/node_modules/vike/dist/esm/node/plugin/plugins/config/index.js:27:54)

**Comment by brillout** [comment]
Fix pre-released in `vike@0.4.149-commit-544b031`.

Btw. would your company be up for [sponsoring](https://github.com/sponsors/vikejs)?

**Comment by AurelienLourot** [comment]
I see @SMKJALLAD is now a sponsor, thanks a lot :)
