### ISSUE TITLE
ReferenceError: __name is not defined

### ISSUE THREAD

**Issue by xar** [vikejs/vike#1346]
### Description

I'm trying to update my project to latest Vike version - 0.4.150 using vue 3.3, vite - 4.5.1. But I'm getting following error when I start SSR server:

```
*** LOG ***
10:36:28 AM [vite] Error when evaluating SSR module /pages/renderer/_all.page.server.ts: failed to import "/src/hooks/Pages/pagesPrepareData.ts"
|- ReferenceError: __name is not defined
    at SortTemplate (eval at cloneSort (/Users/samko/Documents/Web/ayanza/node_modules/source-map-js/lib/quick-sort.js:2:848), <anonymous>:3:107)
    at cloneSort (/Users/samko/Documents/Web/ayanza/node_modules/source-map-js/lib/quick-sort.js:2:892)
    at exports.quickSort (/Users/samko/Documents/Web/ayanza/node_modules/source-map-js/lib/quick-sort.js:2:1101)
    at BasicSourceMapConsumer.SourceMapConsumer_parseMappings [as _parseMappings] (/Users/samko/Documents/Web/ayanza/node_modules/source-map-js/lib/source-map-consumer.js:2:10514)
    at BasicSourceMapConsumer.get [as _generatedMappings] (/Users/samko/Documents/Web/ayanza/node_modules/source-map-js/lib/source-map-consumer.js:2:1045)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/samko/Documents/Web/ayanza/node_modules/source-map-js/lib/source-map-consumer.js:2:2256)
    at mapLines (/Users/samko/Documents/Web/ayanza/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:14:466)
    at doCompileTemplate (/Users/samko/Documents/Web/ayanza/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:13:2424)
    at Object.compileTemplate (/Users/samko/Documents/Web/ayanza/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:13:1055)
    at compile (file:///Users/samko/Documents/Web/ayanza/node_modules/@vitejs/plugin-vue/dist/index.mjs:203:35)
    at transformTemplateInMain (file:///Users/samko/Documents/Web/ayanza/node_modules/@vitejs/plugin-vue/dist/index.mjs:184:18)
    at genTemplateCode (file:///Users/samko/Documents/Web/ayanza/node_modules/@vitejs/plugin-vue/dist/index.mjs:2487:12)
    at transformMain (file:///Users/samko/Documents/Web/ayanza/node_modules/@vitejs/plugin-vue/dist/index.mjs:2341:55)
    at Object.transform (file:///Users/samko/Documents/Web/ayanza/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44352:30)
    at loadAndTransform (file:///Users/samko/Documents/Web/ayanza/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55026:29)
    at instantiateModule (file:///Users/samko/Documents/Web/ayanza/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55951:10)
```

I have type: "module" in my package.json and I'm able to build and do dev without Vike SSR normally.

**Comment by xar** [comment]
When I try to run ssr production build It pass but when I start the server I get

```
Error: [vike@0.4.150][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at assertEnv (file:///Users/samko/Documents/Web/ayanza/node_modules/vike/dist/esm/utils/assertIsNotProductionRuntime.js:38:9)
    at renderPage (file:///Users/samko/Documents/Web/ayanza/node_modules/vike/dist/esm/node/runtime/renderPage.js:36:5)
    at file:///Users/samko/Documents/Web/ayanza/pages/server/index.ts:8:549
    at Layer.handle [as handle_request] (/Users/samko/Documents/Web/ayanza/node_modules/express/lib/router/layer.js:8:864)
    at next (/Users/samko/Documents/Web/ayanza/node_modules/express/lib/router/route.js:8:1411)
    at Route.dispatch (/Users/samko/Documents/Web/ayanza/node_modules/express/lib/router/route.js:8:1100)
    at Layer.handle [as handle_request] (/Users/samko/Documents/Web/ayanza/node_modules/express/lib/router/layer.js:8:864)
    at /Users/samko/Documents/Web/ayanza/node_modules/express/lib/router/index.js:8:3181
    at param (/Users/samko/Documents/Web/ayanza/node_modules/express/lib/router/index.js:8:4352)
    at param (/Users/samko/Documents/Web/ayanza/node_modules/express/lib/router/index.js:8:4525)
    at Function.process_params (/Users/samko/Documents/Web/ayanza/node_modules/express/lib/router/index.js:8:5093)
    at next (/Users/samko/Documents/Web/ayanza/node_modules/express/lib/router/index.js:8:3071)
    at SendStream.error (/Users/samko/Documents/Web/ayanza/node_modules/serve-static/index.js:8:1519)
    at SendStream.emit (node:events:517:28)
    at SendStream.emit (node:domain:489:12)
    at SendStream.error (/Users/samko/Documents/Web/ayanza/node_modules/send/index.js:7:3729)
    at SendStream.onStatError (/Users/samko/Documents/Web/ayanza/node_modules/send/index.js:7:6207)
    at next (/Users/samko/Documents/Web/ayanza/node_modules/send/index.js:7:10757)
    at /Users/samko/Documents/Web/ayanza/node_modules/send/index.js:7:10896
    at FSReqCallback.oncomplete (node:fs:210:21)
```

**Comment by phonzammi** [comment]
Please give some reproduction or steps to reproduce

**Comment by xar** [comment]
sorry. The issue was in the end that project used tsx. After switch to ts-node it works better.
