### ISSUE TITLE
After converting  CSR to SSR  facing a few bugs in my React code, Please help me out. 

### ISSUE THREAD

**Issue by Nithin250594** [vikejs/vike#1414]
### Description

I am getting the below errors, while running npm run dev

 Error when evaluating SSR module /pages/index/App.jsx: failed to import "react-router-dom"
|- Error: Cannot find module 'react-router-dom' imported from '/mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx'
    at nodeImport (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:56088:25)
    at ssrImport (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55990:30)
    at eval (/mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx:5:37)
    at instantiateModule (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:56052:9)
┌─────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────┘
1:18:43 PM [vite-plugin-ssr][request(2)][Error] An error was thrown:
Error: Cannot find module 'react-router-dom' imported from '/mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx'
    at nodeImport (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:56088:25)
    at ssrImport (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55990:30)
    at eval (/mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx:5:37)
    at instantiateModule (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:56052:9) {
  code: 'ERR_MODULE_NOT_FOUND'
}
1:18:43 PM [vite][request(1)] Failed to load url react-router-dom (resolved id: react-router-dom) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx. Does the file exist?
1:18:45 PM [vite][request(1)] Failed to load url react-router-dom (resolved id: react-router-dom) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx. Does the file exist?
1:18:45 PM [vite][request(1)] Failed to load url js-cookie (resolved id: js-cookie) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/ProtectedRoute/index.jsx. Does the file exist?
1:18:45 PM [vite][request(1)] Failed to load url react-loader-spinner (resolved id: react-loader-spinner) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/TrendingRoute/index.jsx. Does the file exist?
1:18:45 PM [vite][request(1)] Failed to load url react-player (resolved id: react-player) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/index.jsx. Does the file exist?
1:18:45 PM [vite][request(1)] Failed to load url date-fns (resolved id: date-fns) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/index.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url react-router-dom (resolved id: react-router-dom) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url styled-components (resolved id: styled-components) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/HomeRoute/styledComponents.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url react-icons/io (resolved id: react-icons/io) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/HomeRoute/styledComponents.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url react-icons/cg (resolved id: react-icons/cg) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url react-icons/hi (resolved id: react-icons/hi) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url react-icons/ai (resolved id: react-icons/ai) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url react-icons/si (resolved id: react-icons/si) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url react-icons/md (resolved id: react-icons/md) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/HomeRoute/styledComponents.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url date-fns (resolved id: date-fns) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/index.jsx. Does the file exist?
1:18:48 PM [vite][request(1)] Failed to load url js-cookie (resolved id: js-cookie) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/ProtectedRoute/index.jsx. Does the file exist?
1:18:49 PM [vite][request(1)] Failed to load url react-icons/si (resolved id: react-icons/si) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
1:18:49 PM [vite][request(1)] Failed to load url styled-components (resolved id: styled-components) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/HomeRoute/styledComponents.jsx. Does the file exist?
1:18:49 PM [vite][request(1)] Failed to load url react-icons/hi (resolved id: react-icons/hi) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
1:18:49 PM [vite][request(1)] Failed to load url react-icons/cg (resolved id: react-icons/cg) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
1:18:49 PM [vite][request(1)] Failed to load url react-icons/ai (resolved id: react-icons/ai) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
1:18:49 PM [vite-plugin-ssr][request(1)] HTTP response / 500
loggedErrors Set(22) {
  Error: Cannot find module 'react-router-dom' imported from '/mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx'
      at nodeImport (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:56088:25)
      at ssrImport (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55990:30)
      at eval (/mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx:5:37)
      at instantiateModule (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:56052:9) {
    code: 'ERR_MODULE_NOT_FOUND'
  },
  Error: Failed to load url react-router-dom (resolved id: react-router-dom) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-router-dom (resolved id: react-router-dom) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url js-cookie (resolved id: js-cookie) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/ProtectedRoute/index.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-loader-spinner (resolved id: react-loader-spinner) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/TrendingRoute/index.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-player (resolved id: react-player) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/index.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url date-fns (resolved id: date-fns) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/index.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-router-dom (resolved id: react-router-dom) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/pages/index/App.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url styled-components (resolved id: styled-components) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/HomeRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/io (resolved id: react-icons/io) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/HomeRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/cg (resolved id: react-icons/cg) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/hi (resolved id: react-icons/hi) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/ai (resolved id: react-icons/ai) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/si (resolved id: react-icons/si) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/md (resolved id: react-icons/md) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/HomeRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url date-fns (resolved id: date-fns) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/index.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url js-cookie (resolved id: js-cookie) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/ProtectedRoute/index.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/si (resolved id: react-icons/si) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url styled-components (resolved id: styled-components) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/HomeRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/hi (resolved id: react-icons/hi) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/cg (resolved id: react-icons/cg) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  },
  Error: Failed to load url react-icons/ai (resolved id: react-icons/ai) in /mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/VideoItemDetailsRoute/styledComponents.jsx. Does the file exist?
      at loadAndTransform (file:///mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55015:21) {
    code: 'ERR_LOAD_URL'
  }
}
swallowedErrorMessages Set(1) {
  'Transform failed with 1 error:\n' +
    '/mnt/c/Users/pnsai/ReactCode/ssr-nxt-watch-project/components/HomeRoute/index.jsx:217:12: ERROR: Expected ";" but found "{"'
}

I really appreciate any help you can provide.

**Comment by brillout** [comment]
I don't think it's related to Vike?

Closing as per https://brillout.github.io/rules/.
