### ISSUE TITLE
Error starting Vike with Hono

### ISSUE THREAD

**Issue by jamiehaywood** [vikejs/vike#1425]
### Description

hi @brillout and maintainers!

Awesome framework - really enjoy using it.

I've been having a look at getting Vike working with Hono (and then hopefully with CloudFlare workers). I've dived into the examples to see how best to tackle this, and I hit an error in the CLI, which encouraged me to raise a bug. I appreciate you're busy, and there's no rush on this - just something I'm exploring. Any pointers one what I need to change in my repo would be greatly appreciated.

## Error:
```
[vike@0.4.156][config][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at file:///Users/jh/code/hono-vike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:100:9
    at Array.map (<anonymous>)
    at loadInterfaceFiles (file:///Users/jh/code/hono-vike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:98:34)
    at loadVikeConfig (file:///Users/jh/code/hono-vike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:233:40)
    at loadVikeConfig_withErrorHandling (file:///Users/jh/code/hono-vike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:196:15)
    at getVikeConfig (file:///Users/jh/code/hono-vike/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:70:12)
    at getConfigVikPromise (file:///Users/jh/code/hono-vike/node_modules/vike/dist/esm/node/plugin/plugins/config/index.js:27:54)
```

## Minimal reproduction repo:
https://github.com/jamiehaywood/hono-vike

**Comment by jamiehaywood** [comment]
so I did a bit of debugging, and I realised I didn't name the page correctly (`+.page.tsx` instead of `+Page.tsx`). Still working on figuring out the integration, but am going to close this, as it's user error not a bug. 

One potential suggestion might be to tell the user to check that they have a correctly named file, but as the idiot who just did this, all you need to do is read the docs 😅

**Comment by brillout** [comment]
> tell the user to check that they have a correctly named file

Done.

> I've been having a look at getting Vike working with Hono (and then hopefully with CloudFlare workers).

Excting. Let us know how that goes. Have a look at https://github.com/vikejs/vike/discussions/1391, and also at https://github.com/vikejs/vike/discussions/1403 which has some insightful discussion about Cloudflare Workers integration.
