### ISSUE TITLE
Error: [vike@0.4.156][Bug] You stumbled upon a bug in Vike's source code.

### ISSUE THREAD

**Issue by arp** [vikejs/vike#1445]
### Description

I followed the guide at https://vike.dev/render and switched from throw RenderErrorPage() to throw render():

```
  throw(status, error)
```

Now when a page is not found, I see this in the logs:

```
7:25:06 PM [vike][request(3)] render("rejected", {"status":404,"data":{"stat...) thrown by onBeforeRender() hook defined at /renderer/+onBeforeRender.tsx while rendering /article/react_devtools_backend_compact.js.map
Error: [vike@0.4.156][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at handleUrl (file:///Users/arp/workspace/letterty/letterty-fml/node_modules/vike/dist/esm/node/runtime/renderPage.js:299:5)
    at getPageContextInitEnhancedSSR (file:///Users/arp/workspace/letterty/letterty-fml/node_modules/vike/dist/esm/node/runtime/renderPage.js:286:53)
    at renderPageAlreadyPrepared (file:///Users/arp/workspace/letterty/letterty-fml/node_modules/vike/dist/esm/node/runtime/renderPage.js:115:41)
    at handleAbortError (file:///Users/arp/workspace/letterty/letterty-fml/node_modules/vike/dist/esm/node/runtime/renderPage.js:399:41)
    at renderPageAlreadyPrepared (file:///Users/arp/workspace/letterty/letterty-fml/node_modules/vike/dist/esm/node/runtime/renderPage.js:149:35)
    at renderPageAndPrepare (file:///Users/arp/workspace/letterty/letterty-fml/node_modules/vike/dist/esm/node/runtime/renderPage.js:101:12)
    at file:///Users/arp/workspace/letterty/letterty-fml/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///Users/arp/workspace/letterty/letterty-fml/node_modules/vike/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///Users/arp/workspace/letterty/letterty-fml/node_modules/vike/dist/esm/node/plugin/shared/addSsrMiddleware.js:18:27
    ```

**Comment by brillout** [comment]
Fix released in `0.4.157`.

It's probably a little too early as your startup is in stealth mode, but would [sponsoring](https://github.com/vikejs/vike/issues/1350) be on the table? That would make a huge impact.
