### ISSUE TITLE
Plugin erro when using it on a quasar.config.js file

### ISSUE THREAD

**Issue by joaoluizmagalhaes** [vikejs/vike#1448]
### Description

I'm trying to install de plugin on a quasar APP and got this error:

If you want changes to quasar.config.js > build > vitePlugins to be picked up, specify them in this form: [ [ 'plugin-name', { /* opts */ } ], ... ] or [ [ pluginFn, { /* opts */ } ], ... ]

/Users/joaoluizdefigueiredomagalhaes/Desktop/Dev/eb/essencia-bahiana/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/resolveBase.js:16
    (0, utils_js_1.assert)(baseOriginal === null || typeof baseOriginal == 'string');
                          ^
Error: [vite-plugin-ssr@0.4.142][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at resolveBase (/Users/joaoluizdefigueiredomagalhaes/Desktop/Dev/eb/essencia-bahiana/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/resolveBase.js:16:27)
    at resolveConfig (/Users/joaoluizdefigueiredomagalhaes/Desktop/Dev/eb/essencia-bahiana/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/index.js:42:73)
    at Object.configResolved (/Users/joaoluizdefigueiredomagalhaes/Desktop/Dev/eb/essencia-bahiana/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/index.js:22:13)
    at async Promise.all (index 3)
    at resolveConfig (/Users/joaoluizdefigueiredomagalhaes/Desktop/Dev/eb/essencia-bahiana/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:61641:5)
    at createServer (/Users/joaoluizdefigueiredomagalhaes/Desktop/Dev/eb/essencia-bahiana/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:60111:20)
    at SpaDevServer.#runVite (/Users/joaoluizdefigueiredomagalhaes/Desktop/Dev/eb/essencia-bahiana/node_modules/@quasar/app-vite/lib/modes/spa/spa-devserver.js:25:20)

I'm trying to use it on :

vitePlugins: [
        ['@intlify/vite-plugin-vue-i18n', {
          // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
          // compositionOnly: false,

          // if you want to use named tokens in your Vue I18n messages, such as 'Hello {name}',
          // you need to set `runtimeOnly: false`
          // runtimeOnly: false,

          // you need to set i18n resource including paths !
          include: path.resolve(__dirname, './src/i18n/**')
        }],
        require('tailwindcss'),
        require('autoprefixer'),
        ssr()

vitePlugins insed Quasar config file

**Comment by brillout** [comment]
Add `console.log('baseOriginal', baseOriginal);` before `/Users/joaoluizdefigueiredomagalhaes/Desktop/Dev/eb/essencia-bahiana/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/resolveBase.js:16` and let me know what you get.

**Comment by joaoluizmagalhaes** [comment]
baseOriginal undefined

**Comment by brillout** [comment]
Does it work if you remove the `assert()` line?

**Comment by joaoluizmagalhaes** [comment]
Sorry, which one?

**Comment by brillout** [comment]
Line 16 (or 17 after you added the console.log)

**Comment by brillout** [comment]
@joaoluizmagalhaes Are you still having issue? I'll re-open if you do.
