### ISSUE TITLE
`jsxDEV` is not a function

### ISSUE THREAD

**Issue by chrisvander** [vikejs/vike#1469]
### Description

After building and Dockerizing a Vike application with `NODE_ENV=production`, the `onRenderHtml` function appears to fail with the following error:

```
TypeError: jsxDEV is not a function
    at onRenderHtml (file:///app/dist/server/chunks/chunk-jCh2fyyV.js:1770:124)
    at file:///app/node_modules/.pnpm/vike@0.4.160_vite@5.0.12/node_modules/vike/dist/esm/node/runtime/renderPage/executeOnRenderHtmlHook.js:15:53
    at file:///app/node_modules/.pnpm/vike@0.4.160_vite@5.0.12/node_modules/vike/dist/esm/shared/hooks/executeHook.js:46:31
    at executeHook (file:///app/node_modules/.pnpm/vike@0.4.160_vite@5.0.12/node_modules/vike/dist/esm/shared/hooks/executeHook.js:55:7)
    at executeOnRenderHtmlHook (file:///app/node_modules/.pnpm/vike@0.4.160_vite@5.0.12/node_modules/vike/dist/esm/node/runtime/renderPage/executeOnRenderHtmlHook.js:15:35)
    at renderPageAlreadyRouted (file:///app/node_modules/.pnpm/vike@0.4.160_vite@5.0.12/node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js:58:36)
    at async renderPageNominal (file:///app/node_modules/.pnpm/vike@0.4.160_vite@5.0.12/node_modules/vike/dist/esm/node/runtime/renderPage.js:268:36)
    at async renderPageAlreadyPrepared (file:///app/node_modules/.pnpm/vike@0.4.160_vite@5.0.12/node_modules/vike/dist/esm/node/runtime/renderPage.js:121:45)
    at async renderPageAndPrepare (file:///app/node_modules/.pnpm/vike@0.4.160_vite@5.0.12/node_modules/vike/dist/esm/node/runtime/renderPage.js:101:12)
    at async renderPage_wrapper (file:///app/node_modules/.pnpm/vike@0.4.160_vite@5.0.12/node_modules/vike/dist/esm/node/runtime/renderPage.js:26:24)
```

Package versions: `vite@^5.0.12`, `vike@0.4.160`. Build script is a simple `vite build`, deployment uses `NODE_ENV=production pnpm dlx tsx ./server/index.ts`.

**Comment by brillout** [comment]
`jsxDEV` doesn't come from Vike, so I don't think it's related to Vike.

It's probably related to `@vitejs/plugin-react`, `react-dom`, or `react`.

I'm closing this issue, but I'll re-open if there is evidence this is related to Vike.

**Comment by chrisvander** [comment]
Thanks for pointing me in the right direction. In case anyone finds this, if the Dockerfile has `NODE_ENV=development` at build time, this error will occur.

**Comment by brillout** [comment]
Thank you for circling back on this. I've added some user friendly error messages that catches this issue early on.

(And thank you for sponsoring 💚)

**Comment by brillout** [comment]
Reproduction: https://github.com/brillout/reprod_jsxDev-not-a-function. It seems that setting `process.env.NODE_ENV` to any value other than `production` triggers the error `TypeError: jsxDEV is not a function`.

**Comment by ajay-circuit** [comment]
How can I make a "dev builds" in Vike — one that uses .env.development instead of .env.production?

I’ve already figured out a way to force it to pick the .env.development file using dotenv, but I’m curious — is there a built-in CLI command or a more official way to specify the environment for the build process?
