### ISSUE TITLE
[vike][Wrong Usage] Loading Vike's Vite plugin (the vike/plugin module) is prohibited in production.

### ISSUE THREAD

**Issue by dcolley** [vikejs/vike#1477]
### Description

Steps to reproduce: scaffold app

```bash
yarn create vike ui3-vike
cd ui3-vike
yarn install
yarn dev          # works fine
yarn server       # works fine
yarn server:prod  # produces this error
```

As soon as I try to load the page in a browser, the server app crashes and I see this in the console.
```bash
Error: [vike][Wrong Usage] Loading Vike's Vite plugin (the vike/plugin module) is prohibited in production.
    at assertEnv (file:///Users/derek/Sites/ui3-vike/node_modules/vike/dist/esm/utils/assertIsNotProductionRuntime.js:50:9)
    at renderPage (file:///Users/derek/Sites/ui3-vike/node_modules/vike/dist/esm/node/runtime/renderPage.js:36:5)
    at file:///Users/derek/Sites/ui3-vike/server/index.ts:50:35
    at Layer.handle [as handle_request] (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/layer.js:95:5)
    at /Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:284:15
    at param (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:421:3)
    at next (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:280:10)
    at /Users/derek/Sites/ui3-vike/node_modules/sirv/build.js:180:28
    at Layer.handle [as handle_request] (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:328:13)
    at /Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:280:10)
    at compression (/Users/derek/Sites/ui3-vike/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:328:13)
    at /Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/Users/derek/Sites/ui3-vike/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:328:13)
    at /Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:280:10)
    at query (/Users/derek/Sites/ui3-vike/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:328:13)
    at /Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/Users/derek/Sites/ui3-vike/node_modules/express/lib/router/index.js:175:3)
    at Function.handle (/Users/derek/Sites/ui3-vike/node_modules/express/lib/application.js:181:10)
    at Server.app (/Users/derek/Sites/ui3-vike/node_modules/express/lib/express.js:39:9)
    at Server.emit (node:events:514:28)
    at Server.emit (node:domain:489:12)
    at parserOnIncoming (node:_http_server:1107:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

**Comment by brillout** [comment]
I cannot reproduce with following steps:

```bash
pnpm create vike@latest
# Select a boilerplate: · react
cd vike-app/
pnpm install
pnpm run server:prod
```

I get following error instead which is expected.

```
Error: ENOENT: no such file or directory, scandir '/home/romu/tmp/vike-app/dist/client'
    at readdirSync (node:fs:1452:3)
    at totalist (/home/romu/tmp/vike-app/node_modules/.pnpm/totalist@3.0.1/node_modules/totalist/sync/index.js:6:12)
    at module.exports (/home/romu/tmp/vike-app/node_modules/.pnpm/sirv@2.0.4/node_modules/sirv/build.js:153:3)
    at startServer (file:///home/romu/tmp/vike-app/server/index.js:32:13) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/romu/tmp/vike-app/dist/client'
}
```

**Comment by brillout** [comment]
I need correct reproduction steps (I think my steps are equivalent to yours), I'll re-open then.

**Comment by dcolley** [comment]
Apologies, I realise I made different selections to you.

```
yarn create vike vike-test
yarn create v1.22.21
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-vike@0.0.325" with binaries:
      - create-vike

Scaffolding project in /Users/derek/Sites/vike-test...
? Select a boilerplate: … 
  vue
❯ vue-ts
  react
  react-ts

Scaffolding project in /Users/derek/Sites/vike-test...
✔ Select a boilerplate: · vue-ts

cd vike-test
npm install
npm run build
nmp run server:prod
```
Works fine... weird 
Thanks for the quick response!

**Comment by brillout** [comment]
No worries and let me know if you can manage to reproduce. Error messages should be helpful.
