### ISSUE TITLE
extractAssets fails on build

### ISSUE THREAD

**Issue by tonyrewin** [vikejs/vike#1480]
### Description

not sure what's wrong, just updated some packages and routes to v1 design

```sh
npm run build

> webapp@0.9.2 build
> vite build

vite v5.0.12 building for production...
✓ 194 modules transformed.
[vike:extractAssets:remove-javaScript] [vike@0.4.161][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
file: /Users/me/code/webapp/src/pages/index.page.server.ts?extractAssets&lang.ts
error during build:
Error: [vike@0.4.161][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at Object.transform (file:///Users/me/code/webapp/node_modules/vike/dist/esm/node/plugin/plugins/extractAssetsPlugin.js:40:17)
    at file:///Users/kindus/code/dev.discours.io/webapp/node_modules/rollup/dist/es/shared/node-entry.js:18692:40
```

**Comment by brillout** [comment]
Does dev work?
