### ISSUE TITLE
Error [RollupError]: Could not resolve "../dist/assets.json" from "renderer/_default.page.server.ts" after upgrade 0.4.161

### ISSUE THREAD

**Issue by nestle49** [vikejs/vike#1501]
### Description

I import manifest inside renderer/_default.page.server.ts:

`const getManifest = import('../dist/assets.json').catch(() => ({ default: {} }))`

After upgrade from 0.4.160 -> 0.4.161 (or higher) I discovered **assets.json** renamed **_temp_manifest.json**

After build error I looked at the changelog again https://github.com/vikejs/vike/blob/main/CHANGELOG.md, but didn't see this change or guid for migration

**Comment by nestle49** [comment]
now assets.json exist, what's happens?

**Comment by DaniilIsupov** [comment]
I have same problem, but only if I install dependencies with production flag
```npm i --production```

**Comment by DaniilIsupov** [comment]
strange thing is that there are still references to `assets.json` in code

[const assetsJsonFilePath = path.posix.join(outDirs.outDirRoot, 'assets.json')](https://github.com/vikejs/vike/blob/8b88d547d69b0f658dfb9aab6f00cb7cc90d5c5d/vike/node/plugin/plugins/buildConfig.ts#L92-L93)

[const assetsJsonFilePath = path.join(dir, '..', 'assets.json')](https://github.com/vikejs/vike/blob/8b88d547d69b0f658dfb9aab6f00cb7cc90d5c5d/vike/node/plugin/plugins/importBuild/index.ts#L72-L73)

**Comment by brillout** [comment]
Let me try to reproduce.

**Comment by brillout** [comment]
I cannot reproduce, can one of you publish a reproduction?

**Comment by brillout** [comment]
> `const getManifest = import('../dist/assets.json').catch(() => ({ default: {} }))`
> 
> After upgrade from 0.4.160 -> 0.4.161 (or higher) I discovered **assets.json** renamed **client/_temp_manifest.json**

The assets JSON should still be emitted at `dist/assets.json`, if it's missing then it's a bug. (Vite say that it's generating `dist/client/_temp_manifest.json` and `dist/server/_temp_manifesrt.json` which is true but Vike merges & moves it to `assets.json`.)

**Comment by nestle49** [comment]
> > `const getManifest = import('../dist/assets.json').catch(() => ({ default: {} }))`
> > After upgrade from 0.4.160 -> 0.4.161 (or higher) I discovered **assets.json** renamed **client/_temp_manifest.json**
> 
> The assets JSON should still be emitted at `dist/assets.json`, if it's missing then it's a bug. (Vite say that it's generating `dist/client/_temp_manifest.json` and `dist/server/_temp_manifesrt.json` which is true but Vike merges & moves it to `assets.json`.)

We will try to reproduce this error, but it is already clear that this does not always happen. That is, sometimes during a build temporary files are not deleted and the resulting file is not created

**Comment by brillout** [comment]
I'll double check the source code for race conditions. I'll report back (ETA today or tomorrow).

**Comment by brillout** [comment]
I don't see any potential race condition in [here](https://github.com/vikejs/vike/blob/744a4af615195d80a8980cf94530ac03ed425545/vike/node/plugin/plugins/buildConfig.ts#L87-L105) (the `writeBundle()` hooks are run in sequence), so I'm not sure how this can happen.

> That is, sometimes during a build temporary files are not deleted and the resulting file is not created

Are there any thrown errors when this happens?

**Comment by DaniilIsupov** [comment]
> I don't see any potential race condition in [here](https://github.com/vikejs/vike/blob/744a4af615195d80a8980cf94530ac03ed425545/vike/node/plugin/plugins/buildConfig.ts#L87-L105) (the `writeBundle()` hooks are run in sequence), so I'm not sure how this can happen.
> 
> > That is, sometimes during a build temporary files are not deleted and the resulting file is not created
> 
> Are there any thrown errors when this happens?

```
x Build failed in 247ms
Error [RollupError]: Could not resolve "../dist/assets.json" from "renderer/_default.page.server.ts"
file: /renderer/_default.page.server.ts
    at getRollupEror (/node_modules/rollup/dist/es/shared/parseAst.js:375:41)
    at error (/node_modules/rollup/dist/es/shared/parseAst.js:372:42)
    at ModuleLoader.handleInvalidResolvedId (/node_modules/rollup/dist/es/shared/node-entry.js:18907:24)
    at ModuleLoader.resolveDynamicImport (/node_modules/rollup/dist/es/shared/node-entry.js:18967:58)
    at /node_modules/rollup/dist/es/shared/node-entry.js:18854:32 {
  code: 'UNRESOLVED_IMPORT',
  exporter: '../dist/assets.json',
  id: '/renderer/_default.page.server.ts',
  watchFiles: [
    '/renderer/_default.page.server.ts',
    '/constants/index.ts',
    '/renderer/app.ts',
    '/package.json',
    '/pages/router.ts',
    '/renderer/usePageContext.ts',
    '/layouts/default.vue'
  ]
}
```

**Comment by brillout** [comment]
Alright, I see what's going on: Rollup is trying to analyze `import('../dist/assets.json')` which resolves to the `assets.json` file but it doesn't exist yet (it's generated after the build ends).

@DaniilIsupov You can try this workaround:

```js
const manifestPath = '../dist/assets.json'
const manifest = await import(manifestPath)
```

@nestle49 I've further enforced the `writeBundle()` execution order df07c4d1b5911392627cf47cc3fc965954fd5fd9 which is pre-released as `vike@0.4.162-commit-8995471`, let me know if you still get the issue.

**Comment by brillout** [comment]
How about this:

```js
const manifestPath = '../dist/ass' + (1 + 1 < 3) && 'ets.json'
const manifest = await import(manifestPath)
```

Rollup shouldn't be able to analyze that.

**Comment by brillout** [comment]
```js
const rollupStaticAnalysisBuster = 1 + 1 < 10 ? '' : 'rollupStaticAnalysisBuster'
let manifest
export async funcion onRenderHtml() {
  manifest = manifest ?? await import("../dist/client/assets.json" + rollupStaticAnalysisBuster)
}
```

Also, I will make the assets manifest available over `pageContext`.

**Comment by brillout** [comment]
https://vike.dev/getGlobalContext released in `0.4.163`.

**Comment by brillout** [comment]
Btw. we're looking for [sponsors](https://github.com/vikejs/vike/issues/1350), in case that's something your company would consider.
