### ISSUE TITLE
`trailingSlash: true` errors when scaffolding a react app with batijs

### ISSUE THREAD

**Issue by schaschko** [vikejs/vike#1502]
### Description

1. Scaffold: `pnpm create @batijs/app --react`

2. Modify `vite.config.ts` to add `trailingSlash: true`:

```ts
import ssr from "vike/plugin";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
// add
import vike from 'vike/plugin'

export default defineConfig({
  plugins: [react({}), ssr({}),
    // add
    vike({
      // Make URLs end with a trailing slash.
      // For example: /some//path -> /some/path/
      trailingSlash: true,
    }),
  ],
});
```

Run:

```
pnpm install
pnpm build
```

Error:

```
> my-app@0.0.1 build /home/fl/tmp/my-app
> vite build

error during build:
Error: [vike][Wrong Usage] Setting config.build.rollupOptions.output.assetFileNames is currently forbidden. (It's possible to support, thus contact a maintainer if you need this.)
    at file:///home/fl/tmp/my-app/node_modules/.pnpm/vike@0.4.162_vite@5.1.3/node_modules/vike/dist/esm/node/plugin/plugins/distFileNames.js:31:21
    at Array.forEach (<anonymous>)
    at configResolved (file:///home/fl/tmp/my-app/node_modules/.pnpm/vike@0.4.162_vite@5.1.3/node_modules/vike/dist/esm/node/plugin/plugins/distFileNames.js:15:27)
    at file:///home/fl/tmp/my-app/node_modules/.pnpm/vite@5.1.3/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:67859:24
    at Array.map (<anonymous>)
    at resolveConfig (file:///home/fl/tmp/my-app/node_modules/.pnpm/vite@5.1.3/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:67859:10)
    at build (file:///home/fl/tmp/my-app/node_modules/.pnpm/vite@5.1.3/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:66730:20)
    at CAC.<anonymous> (file:///home/fl/tmp/my-app/node_modules/.pnpm/vite@5.1.3/node_modules/vite/dist/node/cli.js:842:9)
 ELIFECYCLE  Command failed with exit code 1.
```

I also tried scaffolding a vike app without bati via `pnpm create vike` and then adding `trailingSlash: true`, here everything works. Is this not supported?

**Comment by brillout** [comment]
Thanks for creating the bug report, I will have a look at it tomorrow.

**Comment by schaschko** [comment]
> @schaschko, I'm sorry, but why did you add `import vike from 'vike/plugin'` ? FYI vike already imported with `import ssr from "vike/plugin";`. so you only need to add `trailingSlash: true` inside `ssr({})`

Thank you, this works. I did add it like that, because it's suggested in the [docs](https://vike.dev/url-normalization).

**Comment by brillout** [comment]
@schaschko Make sure to use `0.4.162-commit-6812418` as it includes a bug fix for `trailingSlash`.

Also, in case your company is up for it: https://github.com/vikejs/vike/issues/1350.
