### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by KrisWis** [vikejs/vike#1536]
### Description

    at removeBaseServer (file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/utils/parseUrl-extras.js:31:5)
    at getPermanentRedirect (file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:329:28)
    at renderPageAndPrepare (file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:89:40)
    at file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/server/index.ts:48:29

**Comment by brillout** [comment]
I need the full error including the error message.

**Comment by KrisWis** [comment]
When i wrote `npm run dev`, i got:

> client@0.0.0 dev  
> npm run server:dev


> client@0.0.0 server:dev
> npm run server


> client@0.0.0 server
> node --loader ts-node/esm ./server/index.ts

`(node:4600) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
[vite-plugin-ssr][Warning] The vite-plugin-ssr project has been renamed to Vike, see https://vite-plugin-ssr.com/vike
Server running at http://localhost:3000
14:00:35 [vite-plugin-ssr][request(1)] HTTP request: /
Error: [vite-plugin-ssr@0.4.142][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at removeBaseServer (file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/utils/parseUrl-extras.js:31:5)
    at getPermanentRedirect (file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:329:28)
    at renderPageAndPrepare (file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:89:40)
    at file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///E:/FrontEnd/Sites/ElectroStore/vite-ssr-project/server/index.ts:48:29`

**Comment by brillout** [comment]
Update to the latest version. I'll re-open if you still get the error.

**Comment by KrisWis** [comment]
The same error is still there /;

**Comment by KrisWis** [comment]
> client@0.0.0 dev
> npm run server:dev


> client@0.0.0 server:dev
> npm run server


> client@0.0.0 server
> node --loader ts-node/esm ./server/index.ts

(node:4460) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
[vite-plugin-ssr][Warning] The vite-plugin-ssr project has been renamed to Vike, see https://vite-plugin-ssr.com/vike
Server running at http://localhost:3000
16:58:30 [vite-plugin-ssr][request(1)] HTTP request: /
Error: [vite-plugin-ssr@0.4.142][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at removeBaseServer (file:///E:/FrontEnd/Sites/ElectroStore/client/node_modules/vite-plugin-ssr/dist/esm/utils/parseUrl-extras.js:31:5)
    at getPermanentRedirect (file:///E:/FrontEnd/Sites/ElectroStore/client/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:329:28)
    at renderPageAndPrepare (file:///E:/FrontEnd/Sites/ElectroStore/client/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:89:40)
    at file:///E:/FrontEnd/Sites/ElectroStore/client/node_modules/vite-plugin-ssr/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///E:/FrontEnd/Sites/ElectroStore/client/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///E:/FrontEnd/Sites/ElectroStore/client/server/index.ts:48:29

**Comment by brillout** [comment]
I meant the latest Vike version.
