### ISSUE TITLE
Vite build issue

### ISSUE THREAD

**Issue by ADdinathe** [vikejs/vike#1564]
### Description

I try to build my project with single index.page.tsx, which translated into several languages with i18n.

I tried this guide and got this error
https://vite-plugin-ssr.com/i18n#pre-rendering

Error: [vite-plugin-ssr@0.4.142][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at addUrlComputedProps (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/vite-plugin-ssr/dist/esm/shared/addUrlComputedProps.js:6:5)
    at file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/vite-plugin-ssr/dist/esm/node/prerender/runPrerender.js:402:9
    at Array.forEach (<anonymous>)
    at callOnPrerenderStartHook (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/vite-plugin-ssr/dist/esm/node/prerender/runPrerender.js:394:35)
    at runPrerender (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/vite-plugin-ssr/dist/esm/node/prerender/runPrerender.js:73:5)
    at prerenderFromAutoFullBuild (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/vite-plugin-ssr/dist/esm/node/prerender/runPrerender.js:34:5)
    at triggerFullBuild (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/vite-plugin-ssr/dist/esm/node/plugin/plugins/autoFullBuild.js:80:9)
    at Object.handler (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/vite-plugin-ssr/dist/esm/node/plugin/plugins/autoFullBuild.js:29:25)
    at async Promise.all (index 0)
    at PluginDriver.hookParallel (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/rollup/dist/es/shared/node-entry.js:25347:9)
    at file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/rollup/dist/es/shared/node-entry.js:26659:13
    at catchUnfinishedHookActions (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/rollup/dist/es/shared/node-entry.js:25785:16)
    at build (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/vite/dist/node/chunks/dep-df561101.js:48011:22)
    at CAC.<anonymous> (file:///C:/Users/Mi/WebstormProjects/pubg-front/node_modules/vite/dist/node/cli.js:822:9)
error Command failed with exit code 1.

**Comment by brillout** [comment]
Update to the latest version.
