### ISSUE TITLE
guard() in +config throws bug message

### ISSUE THREAD

**Issue by Mogge** [vikejs/vike#1571]
### Description

```
  at getConfigFileExport (./node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getConfigFileExport.js:8:5)
    at getExtendsImportData (./node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/loadFileAtConfigTime.js:102:30)
    at loadExtendsConfigs (./node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/loadFileAtConfigTime.js:58:31)
    at loadConfigFile (./node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/loadFileAtConfigTime.js:38:56)
    at ./node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:97:52
    at async Promise.all (index 0)
    at loadInterfaceFiles (./node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:92:5)
    at loadVikeConfig (./node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:252:40)
    at loadVikeConfig_withErrorHandling (./node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:215:15)
    at handleReloadSideEffects (./node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:38:9)
```

This is my code in `src/pages/+config.ts`:
```
export { guard }

import type { GuardAsync } from 'vike/types'
import { render } from 'vike/abort'

const guard: GuardAsync = async (pageContext): ReturnType<GuardAsync> => {
  if (pageContext.urlPathname === '/hello/forbidden') {
    throw render(401, 'This page is forbidden.')
  }
}
```

**Comment by Mogge** [comment]
Looks like I need an `export default { guard }` to get it working

**Comment by Mogge** [comment]
Feel free to close this issue.
