### ISSUE TITLE
✘ [ERROR] [vike@0.4.167][Bug] You stumbled upon a Vike bug. Failed to transpile /pages/+config.ts because:

### ISSUE THREAD

**Issue by teukuridho** [vikejs/vike#1576]
### Description

Environment
```
Ubuntu  20.04 x64
Node v20.11.1
```

Dependencies

```
"dependencies": {
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.0",
    "@hattip/adapter-node": "^0.0.44",
    "@mui/icons-material": "^5.15.13",
    "@mui/material": "^5.15.13",
    "@prisma/client": "^5.11.0",
    "@types/body-parser": "^1.19.5",
    "@types/connect-sqlite3": "^0.9.5",
    "@types/express-form-data": "^2.0.5",
    "@types/express-session": "^1.18.0",
    "@types/ping": "^0.4.4",
    "@vitejs/plugin-react": "^4.2.1",
    "axios": "^1.6.8",
    "body-parser": "^1.20.2",
    "connect-sqlite3": "^0.9.15",
    "cross-fetch": "^4.0.0",
    "dayjs": "^1.11.10",
    "dotenv": "^16.4.5",
    "express": "^4.18.3",
    "express-form-data": "^2.0.23",
    "express-session": "^1.18.0",
    "express-validator": "^7.0.1",
    "ping": "^0.4.4",
    "puppeteer": "^22.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "stopwatch-node": "^1.1.0",
    "sweetalert2": "^11.10.6",
    "sweetalert2-react-content": "^5.0.7",
    "swiper": "^11.0.7",
    "tsx": "^4.7.1",
    "vike": "^0.4.167",
    "vike-react": "^0.4.6",
    "vite": "^5.1.6",
    "vite-node": "^1.4.0",
    "vite-plugin-cjs-interop": "^2.1.0",
    "zod": "^3.22.4",
    "zustand": "^4.5.2"
  }
```

Errors
```
 [ERROR] [vike@0.4.167][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours). Debug info (for Vike maintainers; you can ignore this): Not a posix path: (empty string) [plugin vike:externalize-heuristic]

    node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
           ╵                      ^

    at assertPosixPath (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/utils/filesystemPathHandling.js:13:5)
    at toPosixPath (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/utils/filesystemPathHandling.js:6:5)
    at file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:108:41
    at requestCallbacks.on-resolve (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1374:22)
    at handleRequest (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:732:11)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:100:27)
    at handlePlugins (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1293:21)
    at buildOrContextImpl (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:979:5)
    at Object.buildOrContext (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:788:5)
    at /home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:2214:15
    at new Promise (<anonymous>)
    at Object.build (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:2213:25)
    at build (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:2047:51)
    at transpileWithEsbuild (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:165:24)

  The plugin "vike:externalize-heuristic" was triggered by this import

    pages/+config.ts:3:19:
      3 │ import Layout from "../Layouts/IndexLayout";
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~
✘ [ERROR] [vike@0.4.167][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours). Debug info (for Vike maintainers; you can ignore this): Not a posix path: (empty string) [plugin vike:externalize-heuristic]

    node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
           ╵                      ^

    at assertPosixPath (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/utils/filesystemPathHandling.js:13:5)
    at toPosixPath (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/utils/filesystemPathHandling.js:6:5)
    at file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:108:41
    at requestCallbacks.on-resolve (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1374:22)
    at handleRequest (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:732:11)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:100:27)
    at handlePlugins (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1293:21)
    at buildOrContextImpl (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:979:5)
    at Object.buildOrContext (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:788:5)
    at /home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:2214:15
    at new Promise (<anonymous>)
    at Object.build (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:2213:25)
    at build (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:2047:51)
    at transpileWithEsbuild (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:165:24)

  The plugin "vike:externalize-heuristic" was triggered by this import

    pages/+config.ts:4:17:
      4 │ import Head from "../Heads/DefaultHead";
        ╵                  ~~~~~~~~~~~~~~~~~~~~~~
Server listening on http://localhost:3005

```

Strangely, this runs without error in my M1 Pro macbook...
How do I resolve this? thank you 🙏

**Comment by brillout** [comment]
Add the following before line `108` of `file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js` and report back the log results.

```diff
                        const resolved = await build.resolve(path, opts);
+ console.log('args', args);
+ console.log('resolved', resolved);
                        resolved.path = toPosixPath(resolved.path);

**Comment by teukuridho** [comment]
thank you for quick response, here it is

```
args {
  path: '../../Heads/DefaultHead',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/admin/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/admin',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../../Heads/DefaultHead"'
    }
  ],
  warnings: [],
  path: '',
  external: false,
  sideEffects: false,
  namespace: '',
  suffix: '',
  pluginData: undefined
}
args {
  path: '../../../Heads/DefaultHead',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/admin/login/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/admin/login',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../../../Heads/DefaultHead"'
    }
  ],
  warnings: [],
  path: '',
  external: false,
  sideEffects: false,
  namespace: '',
  suffix: '',
  pluginData: undefined
}
args {
  path: 'vike-react/config',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [],
  warnings: [],
  path: '/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike-react@0.4.6_react-dom@18.2.0_react@18.2.0_vike@0.4.167_vite@5.1.6/node_modules/vike-react/dist/+config.js',
  external: false,
  sideEffects: true,
  namespace: 'file',
  suffix: '',
  pluginData: undefined
}
args {
  path: 'vike-react/config',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/slides/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/slides',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [],
  warnings: [],
  path: '/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike-react@0.4.6_react-dom@18.2.0_react@18.2.0_vike@0.4.167_vite@5.1.6/node_modules/vike-react/dist/+config.js',
  external: false,
  sideEffects: true,
  namespace: 'file',
  suffix: '',
  pluginData: undefined
}
args {
  path: '../../../Heads/DefaultHead',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/admin/dashboard/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/admin/dashboard',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../../../Heads/DefaultHead"'
    }
  ],
  warnings: [],
  path: '',
  external: false,
  sideEffects: false,
  namespace: '',
  suffix: '',
  pluginData: undefined
}
args {
  path: '../../Layouts/AdminLayout',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/admin/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/admin',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../../Layouts/AdminLayout"'
    }
  ],
  warnings: [],
  path: '',
  external: false,
  sideEffects: false,
  namespace: '',
  suffix: '',
  pluginData: undefined
}
args {
  path: '../../../Layouts/AdminLayout',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/admin/login/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/admin/login',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../../../Layouts/AdminLayout"'
    }
  ],
  warnings: [],
  path: '',
  external: false,
  sideEffects: false,
  namespace: '',
  suffix: '',
  pluginData: undefined
}
args {
  path: '../Layouts/IndexLayout',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../Layouts/IndexLayout"'
    }
  ],
  warnings: [],
  path: '',
  external: false,
  sideEffects: false,
  namespace: '',
  suffix: '',
  pluginData: undefined
}
args {
  path: '../../Layouts/SlidesLayout',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/slides/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/slides',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../../Layouts/SlidesLayout"'
    }
  ],
  warnings: [],
  path: '',
  external: false,
  sideEffects: false,
  namespace: '',
  suffix: '',
  pluginData: undefined
}
5:36:23 PM [vike][config] Failed to transpile /pages/slides/+config.ts because:
✘ [ERROR] [vike@0.4.167][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours). Debug info (for Vike maintainers; you can ignore this): Not a posix path: (empty string) [plugin vike:externalize-heuristic]

    node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
           ╵                      ^

    at assertPosixPath (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/utils/filesystemPathHandling.js:13:5)
    at toPosixPath (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/utils/filesystemPathHandling.js:6:5)
    at file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:110:41
    at requestCallbacks.on-resolve (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1374:22)
    at handleRequest (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:732:11)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:100:27)
    at handlePlugins (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1293:21)
    at buildOrContextImpl (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:979:5)
    at Object.buildOrContext (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:788:5)
    at /home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:2214:15
    at new Promise (<anonymous>)
    at Object.build (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:2213:25)
    at build (/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:2047:51)
    at transpileWithEsbuild (file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:167:24)

  The plugin "vike:externalize-heuristic" was triggered by this import

    pages/slides/+config.ts:3:20:
      3 │ import  Layout from "../../Layouts/SlidesLayout";
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
args {
  path: '../../../Layouts/AdminDashboardLayout',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/admin/dashboard/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/admin/dashboard',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../../../Layouts/AdminDashboardLayout"'
    }
  ],
  warnings: [],
  path: '',
  external: false,
  sideEffects: false,
  namespace: '',
  suffix: '',
  pluginData: undefined
}
args {
  path: '../Heads/DefaultHead',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../Heads/DefaultHead"'
    }
  ],
  warnings: [],
  path: '',
  external: false,
  sideEffects: false,
  namespace: '',
  suffix: '',
  pluginData: undefined
}
args {
  path: 'vike-react/config',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/admin/login/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/admin/login',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [],
  warnings: [],
  path: '/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike-react@0.4.6_react-dom@18.2.0_react@18.2.0_vike@0.4.167_vite@5.1.6/node_modules/vike-react/dist/+config.js',
  external: false,
  sideEffects: true,
  namespace: 'file',
  suffix: '',
  pluginData: undefined
}
args {
  path: 'vike-react/config',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/admin/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/admin',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [],
  warnings: [],
  path: '/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike-react@0.4.6_react-dom@18.2.0_react@18.2.0_vike@0.4.167_vite@5.1.6/node_modules/vike-react/dist/+config.js',
  external: false,
  sideEffects: true,
  namespace: 'file',
  suffix: '',
  pluginData: undefined
}
args {
  path: 'vike-react/config',
  importer: '/home/teuku/Projects/vike-unilever-ert/pages/admin/dashboard/+config.ts',
  namespace: 'file',
  resolveDir: '/home/teuku/Projects/vike-unilever-ert/pages/admin/dashboard',
  kind: 'import-statement',
  pluginData: undefined
}
resolved {
  errors: [],
  warnings: [],
  path: '/home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike-react@0.4.6_react-dom@18.2.0_react@18.2.0_vike@0.4.167_vite@5.1.6/node_modules/vike-react/dist/+config.js',
  external: false,
  sideEffects: true,
  namespace: 'file',
  suffix: '',
  pluginData: undefined
}
Server listening on http://localhost:3005
```

**Comment by brillout** [comment]
If you replace line `108` (i.e. now line `110`) with `            if (resolved.path) resolved.path = toPosixPath(resolved.path);` what do you get then?

**Comment by teukuridho** [comment]
The code now
```
const resolved = await build.resolve(path, opts);
console.log('args', args);
console.log('resolved', resolved);
// resolved.path = toPosixPath(resolved.path);
if (resolved.path) resolved.path = toPosixPath(resolved.path);
```

What I got
```
> my-app@0.0.1 dev /home/teuku/Projects/vike-unilever-ert
> tsx ./express-entry.ts

failed to load config from /home/teuku/Projects/vike-unilever-ert/vite.config.ts
file:///home/teuku/Projects/vike-unilever-ert/node_modules/.pnpm/vike@0.4.167_vite@5.1.6/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.js:1
-export { transpileAndExecuteFile };
 ^^^^^^

SyntaxError: Unexpected token 'export'
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:167:18)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)

Node.js v20.11.1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by brillout** [comment]
Seems like you made a typo somewhere.

**Comment by teukuridho** [comment]
Before upgrading to the latest version, this is what I got
```
4:48:40 PM [vike][config][Wrong Usage] The import path '../Heads/DefaultHead' in /pages/+config.ts couldn't be resolved: does '../Heads/DefaultHead' point to an existing file?
Server listening on http://localhost:3005
```

My` /pages/+config.ts`
```
import { Config } from "vike/types";
import vikeReact from 'vike-react/config'
import Layout from "../Layouts/IndexLayout";
import Head from "../Heads/DefaultHead";
export default {
    Layout,
    Head,
    title: 'Unilever ERT',
    extends: vikeReact,
} satisfies Config
```

all imports resolveable (I can command click it) and everything runs without error on my macbook, but on Ubuntu not...

**Comment by teukuridho** [comment]
you're right, I made a typo, one of my folder is empty because I included it in .gitignore, I feel so stupid now haha, also maybe the error could be more specific. ie; which imports are missing

thank you anyway

**Comment by brillout** [comment]
>  the error could be more specific. ie; which imports are missing

Agreed & done.
