### ISSUE TITLE
Bug encountered when updating from vike@0.4.150 to vike@0.4.167

### ISSUE THREAD

**Issue by Jearce** [vikejs/vike#1580]
### Description

I recently tried to update Vike from 0.4.150 to 0.4.167 and encountered a bug that Vike caught. Reverting to 0.4.150, the application works fine. As suggested by the error message, here is the error:
```
Error: [vike@0.4.167][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at assertIsNpmPackageImport (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/node_modules/.pnpm/vike@0.4.167_vite@5.0.7/node_modules/vike/dist/esm/utils/isNpmPackage.js:22:5)
    at file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/node_modules/.pnpm/vike@0.4.167_vite@5.0.7/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/determineOptimizeDeps.js:55:21
    at Array.forEach (<anonymous>)
    at file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/node_modules/.pnpm/vike@0.4.167_vite@5.0.7/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/determineOptimizeDeps.js:38:59
    at Array.forEach (<anonymous>)
    at getPageDeps (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/node_modules/.pnpm/vike@0.4.167_vite@5.0.7/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/determineOptimizeDeps.js:37:21)
    at determineOptimizeDeps (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/node_modules/.pnpm/vike@0.4.167_vite@5.0.7/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/determineOptimizeDeps.js:12:40)
    at configResolved (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/node_modules/.pnpm/vike@0.4.167_vite@5.0.7/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/index.js:57:17)
    at async Promise.all (index 6)
    at resolveConfig (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/node_modules/.pnpm/vite@5.0.7/node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:67363:5)
    at _createServer (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/node_modules/.pnpm/vite@5.0.7/node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:59634:20)
    at createBrlVikeApp (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/server/index.js:231:7)
    at Object.build (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/server/index.js:90:17)
    at Object.start (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/server/index.js:62:17)
    at run (file:///home/jessiearce/projects/webstorm/gitlab/node/nano-ui/server/index.js:44:10)
```

**Comment by Jearce** [comment]
This is the result:
```
definedAt {
  importPathAbsolute: '#root/layouts/LoginLayout.vue',
  filePathAbsoluteUserRootDir: null,
  filePathAbsoluteFilesystem: null,
  filePathAbsoluteVite: '#root/layouts/LoginLayout.vue',
  filePathToShowToUser: '#root/layouts/LoginLayout.vue',
  fileExportName: 'default',
  fileExportPathToShowToUser: []
}
```

**Comment by brillout** [comment]
Hm, that's surprising. Can you publish a reproduction?

**Comment by Jearce** [comment]
Yes, here is a reproduction: https://github.com/Jearce/vike-reproduction-issue-1580.git.

**Comment by brillout** [comment]
Fix pre-relased as `0.4.167-commit-4996ef0`.

Also make sure to apply this: https://github.com/vikejs/vike/issues/1584#issuecomment-2027096361.

**Comment by brillout** [comment]
(Not sure but I think I asked you already before but in case I didn't and your company is up for we're looking for [sponsors](https://github.com/vikejs/vike/issues/1350). It makes a massive difference!)

**Comment by Jearce** [comment]
Awesome! That fixed the issue. Thank you. I am an individual sponsor now.

**Comment by brillout** [comment]
Ok great. Let me know if you run into other issues, and thank you for sponsoring :green_heart:
