### ISSUE TITLE
HRM issue after changing one character in default setup

### ISSUE THREAD

**Issue by WulfP** [vikejs/vike#1589]
### Description

What I did:

In a WSL-2 Terminal (Win 10) with Ubuntu-22-04 and node v18.14.2:

`pnpm create @batijs/app --vue --tailwindcss --express --eslint --prettier`
`cd my-app/`
`pnpm install`
`code .`
`pnpm run dev`

In VSCode I changed
`<li>Rendered to HTML.</li>`
to
`<li>Rendered to HTML!</li>`

After `<Ctrl-S>` I got:

Error: [vike@0.4.168][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at getFilePathAbsoluteUserRootDir (file:///home/wulf/projekte/bati/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.7/node_modules/vike/dist/esm/node/plugin/shared/getFilePath.js:90:5)
    at getFilePathResolved (file:///home/wulf/projekte/bati/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.7/node_modules/vike/dist/esm/node/plugin/shared/getFilePath.js:18:39)
    at reloadConfig (file:///home/wulf/projekte/bati/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.7/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/index.js:122:50)
    at listener (file:///home/wulf/projekte/bati/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.7/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/index.js:77:13)
    at FSWatcher.<anonymous> (file:///home/wulf/projekte/bati/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.7/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/index.js:66:50)
    at FSWatcher.emit (node:events:525:35)
    at FSWatcher.emit (node:domain:489:12)
    at FSWatcher.emitWithAll (file:///home/wulf/projekte/bati/my-app/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:45880:8)
    at FSWatcher._emit (file:///home/wulf/projekte/bati/my-app/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:45972:8)
    at NodeFsHandler._handleFile (file:///home/wulf/projekte/bati/my-app/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:44557:14)
    at NodeFsHandler._addToNodeFs (file:///home/wulf/projekte/bati/my-app/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:44794:21)
 ELIFECYCLE  Command failed with exit code 1.

Thx!

**Comment by brillout** [comment]
Insert the following before line `90` of `/home/wulf/projekte/bati/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.7/node_modules/vike/dist/esm/node/plugin/shared/getFilePath.js` and report back. (It seems to be a Windows issue but I don't have a Windows setup atm.)

```diff
+ console.log('filePathAbsoluteFilesystem', filePathAbsoluteFilesystem);
+ console.log('userRootDir', userRootDir);
+ console.log('filePathRelative', filePathRelative);    
    assert(!filePathRelative.startsWith('.') && !filePathRelative.startsWith('/'));
```

**Comment by WulfP** [comment]
Thanks for this super fast response!

I don´t expect a Windows-issue. WSL is the "Windows subsystem for Linux" and provides a native Linux-VM including original Filesystem similar to what you get inside a docker container. So the developement is done in Ubuntu 22.04.

After inserting the thee new commands I see this log between server start end error exit:
```
Server listening on http://localhost:3000
filePathAbsoluteFilesystem /home/wulf/projekte/bati/my-app/.history/pages/index/+Page_20240402105314.vue
userRootDir /home/wulf/projekte/bati/my-app
filePathRelative .history/pages/index/+Page_20240402105314.vue
Error: [vike@0.4.168][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new ...
```

**Comment by brillout** [comment]
Indeed, it isn't a Windows issue.

What is the `.history/` directory and the `+Page_20240402105314.vue` file? Is that a Tailwind thing?

**Comment by brillout** [comment]
> line `90` of `/home/wulf/projekte/bati/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.7/node_modules/vike/dist/esm/node/plugin/shared/getFilePath.js`

If you remove the assertion `   assert(!filePathRelative.startsWith('.') && !filePathRelative.startsWith('/'));` does it work then?

**Comment by WulfP** [comment]
Bingo! That´s it. No issues anymore after removing the assertion!
Great work! I did not notice `.history` in the error message.

.history is created by VS-Code local history plugin and should not be included.

But expect this to be present on many machines. It can be extremely useful even if git is active.

After removing .history and editing +Page.vue with another editor, HMR was working fine.

I investigated if adding `.history` to .gitignore helps. Some tools respect these entries.
But here it did not show any effect. HMR still crashed the dev-server.

So it should be possible to restrict the directories that were parsed during HMR, right?

**Comment by brillout** [comment]
Fix pre-released as `vike@0.4.168-commit-ce94f5c`.

> adding `.history` to .gitignore

That should actually make Vike ignore `.history`.

Related: https://github.com/vikejs/vike/issues/1593.

Let me know if you still run into issues.

In case that's something your company be up for, we're looking for [sponsors](1350) &mdash; it makes a massive difference.

**Comment by WulfP** [comment]
Thank your for your quick help!

I will continue to evaluate vike and see if we can use it for our project.
Currently our company is a bit too far away from break even to think about sponsoring.
But I will keep it in mind!

Btw: Grüße in die alte Heimat!

**Comment by brillout** [comment]
Makes sense and thanks for circling back on this.

Grüße zurück :)
