### ISSUE TITLE
Bug reported due to HMR overlay

### ISSUE THREAD

**Issue by abelgibayev** [vikejs/vike#1606]
### Description

vite.config.ts
```
import ssr from "vike/plugin";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [react({}), ssr({}), tsconfigPaths()],
  ssr: {
    noExternal: ["styled-components"],
  },
});

```
The error itself
```
/Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/pageFiles.js

    at isVirtualFileId (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.8/node_modules/vike/dist/esm/utils/virtual-files.js:13:5)
    at Context.resolveId (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.8/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/index.js:31:17)
    at Object.resolveId (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51096:64)
    at Context.resolve (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50787:23)
    at viteResolve (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite-tsconfig-paths@4.3.2_typescript@5.4.5_vite@5.2.8/node_modules/vite-tsconfig-paths/src/index.ts:162:12)
    at file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite-tsconfig-paths@4.3.2_typescript@5.4.5_vite@5.2.8/node_modules/vite-tsconfig-paths/src/index.ts:327:16
    at Context.resolveId (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite-tsconfig-paths@4.3.2_typescript@5.4.5_vite@5.2.8/node_modules/vite-tsconfig-paths/src/index.ts:172:43)
    at Object.resolveId (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51096:32)
    at Context.resolve (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50787:23)
    at Context.handler (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.8/node_modules/vike/dist/esm/node/plugin/plugins/fileEnv.js:35:34)
    at Object.resolveId (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51096:32)
    at TransformContext.resolve (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:50787:23)
    at normalizeUrl (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66083:34)
    at file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66247:47
    at async Promise.all (index 1)
    at TransformContext.transform (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:66168:13)
    at Object.transform (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51172:30)
    at loadAndTransform (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:53923:29)
    at viteTransformMiddleware (file:///Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vite@5.2.8/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:63775:32

```

**Comment by brillout** [comment]
Insert the following before line `13` of `/Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_vite@5.2.8/node_modules/vike/dist/esm/utils/virtual-files.js` and report back the log result.

```diff
+   console.log('id', id);
    assert(!id.includes(idBase));
```

**Comment by brillout** [comment]
I'll re-open after I get more information on this.

**Comment by abelgibayev** [comment]
```
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/history.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/renderPageClientSide.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/onBrowserHistoryNavigation.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/onLinkClick.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/scrollRestoration.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/setScrollPosition.js?v=d8ca7672
9:44:33 PM [vike][request(3)] HTTP request: /node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/pageFiles.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/createErrorWithCleanStackTrace.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/unique.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/humanizeTime.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/server-routing-runtime/onLoad.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/checkType.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/assertIsBrowser.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/getExports.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/setPageFiles.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/getAllPageIdFiles.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/skipLink.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/getPageContextFromHooks.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/createPageContext.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/prefetch.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/shared/executeOnRenderClientHook.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/hooks/getHook.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/shared/loadUserFilesClientSide.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/abort.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/index.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/isClientSideRoutable.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/error-page.js?v=d8ca7672
9:44:33 PM [vike][request(3)] HTTP response /node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/pageFiles.js?v=d8ca7672 404
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/isNodeJS.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/isScriptFile.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/utils.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/assert_exports_old_design.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/helpers.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/assertPageFilePath.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/parseGlobResults.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/getBaseServer.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/prefetch/getPrefetchSettings.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/prefetch/alreadyPrefetched.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/noRouteMatch.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/utils.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/addUrlComputedProps.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/resolvePrecedence.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/resolveRouteString.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/resolveRouteFunction.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/executeOnBeforeRouteHook.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/debug.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/loadPageRoutes.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/analyzePageClientSide.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/findPageConfig.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/analyzeClientSide.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/json-serializer/parse
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/json-serializer/parse
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/shared/getPageContextSerializedInHtml.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/analyzePageServerSide.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/shared/preparePageContextForUserConsumptionClientSide.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/client-routing-runtime/getPageContext/removeBuiltInOverrides.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageContextRequestUrl.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/assertOnBeforeRenderHookReturn.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/executeGuardHook.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/misc/pageContextInitIsPassedToClient.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/misc/isServerSideError.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/json-serializer/parse
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/@brillout+json-serializer@0.5.8/node_modules/@brillout/json-serializer/dist/esm/parse.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/loadConfigValues.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/sorter.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/compareString.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/isNotNullish.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/stringifyStringArray.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/filesystemPathHandling.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/cast.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/isPropertyGetter.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/isPromise.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/getValuePrintable.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/escapeRegex.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/helpers/getConfigDefinedAtString.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/helpers/getConfigValue.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/getPageFileObject.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/fileTypes.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/serialize/assertPageConfigsSerialized.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/serialize/parsePageConfigs.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/isObjectWithKeys.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/isStringRecord.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/joinEnglish.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/truncateString.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/assertPageContextProvidedByUser.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/analyzePageClientSide/analyzeExports.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/analyzePageClientSide/determineClientEntry.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/getPageFiles/analyzePageClientSide/getExportNames.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/route/deduceRouteStringFromFilesystemPath.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/json-serializer/parse
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/json-serializer/parse
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/json-serializer/parse
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/sortPageContext.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/addIs404ToPageProps.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/client/shared/getPageContextProxyForUser.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/utils/urlToFile.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/assertHookReturnedObject.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/serialize/parseConfigValuesImported.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/serialize/parseConfigValuesSerialized.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/@brillout+json-serializer@0.5.8/node_modules/@brillout/json-serializer/dist/esm/types.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/getExportPath.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/determinePageIdOld.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/page-configs/assertPlusFileExport.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/json-serializer/parse
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/json-serializer/parse
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/json-serializer/parse
id /Users/abelgibayev/Work/iwbl/my-app/node_modules/.pnpm/vike@0.4.168_react-streaming@0.3.24_vite@5.2.8/node_modules/vike/dist/esm/shared/notSerializable.js?v=d8ca7672
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
id /Users/abelgibayev/Work/iwbl/my-app/@brillout/picocolors
```

The problem occurs only if I use `vite-tsconfig-paths`
