### ISSUE TITLE
UncaughtException issue

### ISSUE THREAD

**Issue by Tom208** [vikejs/vike#1608]
### Description

```
Error: [vike@0.4.156][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
at extractFromPath (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage/logHintForCjsEsmError.js:228:5)
at extractFromNodeModulesPath (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage/logHintForCjsEsmError.js:244:25)
at getPackageName_stack1 (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage/logHintForCjsEsmError.js:192:12)
at isCjsEsmError (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage/logHintForCjsEsmError.js:52:32)
at getHint (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage/logHintForCjsEsmError.js:21:17)
at logHintForCjsEsmError (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage/logHintForCjsEsmError.js:12:18)
at onRuntimeError (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage/loggerProd.js:24:5)
at logErrorProd (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage/loggerProd.js:19:5)
at renderPageAlreadyPrepared (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage.js:126:13)
at async renderPageAndPrepare (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage.js:101:12)
at async renderPage_wrapper (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage.js:26:24)
at async renderPage (file:///app/node_modules/vike/dist/esm/node/runtime/renderPage.js:46:50)
at async file:///app/server/index.js:208:25
```

**Comment by brillout** [comment]
Update to the latest version and let me know if you still get this. I'll re-open if you do.
