### ISSUE TITLE
Error previewing built Vike app when using Vite Legacy plugin

### ISSUE THREAD

**Issue by christowiz** [vikejs/vike#1643]
### Description

Received an error message when running `vite preview`.  I added the following to the `plugins` array:
```js
    legacy({
      renderModernChunks: false
    }),
```

This is based on the https://github.com/brillout/vike-with-svelte example repo.

Error message:
```
Debug info (for Vike maintainers; you can ignore this): {"manifestKeys":["__onRenderClient-legacy-6ddb526a.js","node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/client/client-routing-runtime/entry-legacy.js","virtual:vike:pageConfigValuesAll:client:/pages/about-legacy","virtual:vike:pageConfigValuesAll:client:/pages/index-legacy","vite/legacy-polyfills-legacy"],"id":"@@vike/dist/esm/client/client-routing-runtime/entry.js"}
    at getManifestEntry (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage/getPageAssets/getManifestEntry.js:12:9)
    at resolveClientEntriesProd (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage/getPageAssets.js:125:31)
    at file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage/getPageAssets.js:24:63
    at Array.map (<anonymous>)
    at getPageAssets (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage/getPageAssets.js:24:42)
    at Object.__getPageAssets (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage/loadPageFilesServerSide.js:36:42)
    at getHtmlTags (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/html/injectAssets/getHtmlTags.js:16:42)
    at injectHtmlTagsToString (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/html/injectAssets.js:8:28)
    at renderDocumentHtml (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/html/renderHtml.js:38:38)
    at executeOnRenderHtmlHook (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage/executeOnRenderHtmlHook.js:33:24)
    at renderPageAlreadyRouted (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js:56:30)
    at renderPageNominal (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage.js:257:36)
    at renderPageAlreadyPrepared (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage.js:113:45)
    at renderPageAndPrepare (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage.js:93:12)
    at file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///Users/christowiz/tmp/vike-with-svelte/node_modules/.pnpm/vike@0.4.143_vite@4.5.3/node_modules/vike/dist/esm/node/plugin/shared/addSsrMiddleware.js:18:27
3:33:38 PM [vike][request(4)] HTTP response / ERR
```

**Comment by brillout** [comment]
I see. It's on the radar to improve the DX around the legacy plugin: https://github.com/vikejs/vike/discussions/1607#discussioncomment-9184789. I'll then also have a look at this.

In the meantime, is not using `renderModernChunks: false` an option for you?

PR welcome.

**Comment by brillout** [comment]
Is that still an issue? I'll re-open if it is.
