### ISSUE TITLE
Prerender / Static Site Generation with Apollo Queries?

### ISSUE THREAD

**Issue by invertedvisuals** [vikejs/vike#166]
Is it possible to use static site generation as [outlined here](https://vite-plugin-ssr.com/netlify) with static queries like Apollo. I tried using the graphql-apollo example with the command:

`vite build && vite build --ssr && vite-plugin-ssr prerender`

But I'm getting Invariant Violation errors, so I'm wondering if this isn't possible with this library.

```
C:\vite-plugin-ssr\examples\graphql-apollo\node_modules\vite-plugin-ssr\dist\cjs\node\cli\bin.js:30
    throw rejectValue;
    ^

Invariant Violation: Invariant Violation: 28 (see https://github.com/apollographql/invariant-packages)
    at new InvariantError (C:\vite-plugin-ssr\examples\graphql-apollo\node_modules\ts-invariant\lib\invariant.js:16:28)
    at Object.invariant (C:\vite-plugin-ssr\examples\graphql-apollo\node_modules\ts-invariant\lib\invariant.js:28:15)
    at Object.children (C:\vite-plugin-ssr\examples\graphql-apollo\node_modules\@apollo\client\react\context\context.cjs.js:58:78)
    at a.b.render (C:\vite-plugin-ssr\examples\graphql-apollo\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:44:213)     
    at a.b.read (C:\vite-plugin-ssr\examples\graphql-apollo\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)        
    at exports.renderToStaticMarkup (C:\vite-plugin-ssr\examples\graphql-apollo\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:51:446)
    at C:\vite-plugin-ssr\examples\graphql-apollo\node_modules\@apollo\client\react\ssr\ssr.cjs.js:105:21
    at new Promise (<anonymous>)
    at process (C:\vite-plugin-ssr\examples\graphql-apollo\node_modules\@apollo\client\react\ssr\ssr.cjs.js:103:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  framesToPop: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thanks!

**Comment by brillout** [comment]
Hm, not sure. This seems to be more of an Apollo problem than a vite-plugin-ssr one?

**Comment by invertedvisuals** [comment]
I ended up using the uqrl starter instead of Apollo and that worked for SSG, thanks!
