### ISSUE TITLE
Breaking node.js 16 change in 0.4.172

### ISSUE THREAD

**Issue by arthurgailes** [vikejs/vike#1663]
### Description

Hello,

Upgrading from 171 to 172 returns the following error. Not sure if this is a bug or a documentation issue.

```
Error: [vike][Wrong Usage] Node.js 16.18.0 isn't supported, use Node.js >= 18.0.0 instead.
    at assertVersion (file:///mypath/Documents/sites/aei-js-monorepo/node_modules/.pnpm/vike@0.4.172_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/utils/assertVersion.js:5:5)
    at assertNodeVersion (file:///mypath/Documents/sites/aei-js-monorepo/node_modules/.pnpm/vike@0.4.172_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/utils/assertNodeVersio    at onLoad (file:///mypath/Documents/sites/aei-js-monorepo/node_modules/.pnpm/vike@0.4.172_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/node/runtime/onLoad.js:7:5)      
    at file:///mypath/Documents/sites/aei-js-monorepo/node_modules/.pnpm/vike@0.4.172_react-streaming@0.3.14_vite@4.4.9/node_modules/vike/dist/esm/node/runtime/utils.js:4:1
    at async Promise.all (index 0)
```

**Comment by brillout** [comment]
Node.js 16 is EOL and thus not supported anymore.

**Comment by brillout** [comment]
I agree and the plan is to be more strict regarding breaking changes starting from `v1.0.0`. Maybe/tentatively the V1 won't have any major breaking changes for years (since Vike core is decoupled from the UI framework), but let's see how things evolve.

Btw. would your company be up for [sponsoring](https://github.com/vikejs/vike/issues/1350)? As you can imagine, getting the overall architecture and all the details right isn't trivial, to say the least. Any help from companies is massively appreciated!

**Comment by arthurgailes** [comment]
I'm sorry, but mine is mostly a solo project. If I have a feature request in the future, I might be able to send you a small one-time donation.
