### ISSUE TITLE
I got this error after running npm run build

### ISSUE THREAD

**Issue by devburna** [vikejs/vike#1694]
### Description

at Object.writeBundle (/node_modules/vite-plugin-ssr/dist/esm/node/plugin/plugins/buildConfig.js:54:17)
    at /node_modules/rollup/dist/es/shared/node-entry.js:19597:40
    at async Promise.all (index 2)
    at PluginDriver.hookParallel (/node_modules/rollup/dist/es/shared/node-entry.js:19525:9)
    at /node_modules/rollup/dist/es/shared/node-entry.js:20521:13
    at catchUnfinishedHookActions (/node_modules/rollup/dist/es/shared/node-entry.js:19942:16)
    at build (/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:67481:22)
    at CAC.<anonymous> (/node_modules/vite/dist/node/cli.js:842:9)

**Comment by brillout** [comment]
I need the full error message & stack.

**Comment by devburna** [comment]
x Build failed in 18.58s
error during build:
Error: [vite-plugin-ssr@0.4.142][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at Object.writeBundle (/node_modules/vite-plugin-ssr/dist/esm/node/plugin/plugins/buildConfig.js:54:17)
    at /node_modules/rollup/dist/es/shared/node-entry.js:19597:40
    at async Promise.all (index 2)
    at PluginDriver.hookParallel (/node_modules/rollup/dist/es/shared/node-entry.js:19525:9)
    at /node_modules/rollup/dist/es/shared/node-entry.js:20521:13
    at catchUnfinishedHookActions (/node_modules/rollup/dist/es/shared/node-entry.js:19942:16)
    at build (/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:67481:22)
    at CAC.<anonymous> (/node_modules/vite/dist/node/cli.js:842:9)
    
    Stack is Laravel Inertia with React and capacitor

**Comment by brillout** [comment]
Updated to the latest version. I'll re-open if you still get an error then.
