### ISSUE TITLE
I got this error after running npm run build

### ISSUE THREAD

**Issue by amumufun** [vikejs/vike#1721]
### Description

md-vike % npm start

> my-midway-esm-project@1.0.0 start
> cross-env NODE_ENV=production node ./bootstrap.js

2024-06-28 11:55:33.721 ERROR 30633 Error: [vike@0.4.177][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at Dt (file:///md-vike/dist/client/assets/entries/entry-client-routing.D3rq4nRt.js:3:25545)
    at Zr (file:///md-vike/dist/client/assets/entries/entry-client-routing.D3rq4nRt.js:3:25590)
    at file:///md-vike/dist/client/assets/entries/entry-client-routing.D3rq4nRt.js:3:26982
    at async loadModule (/md-vike/node_modules/@midwayjs/core/dist/util/index.js:96:28)
    at async ESModuleFileDetector.loadAsync (/md-vike/node_modules/@midwayjs/core/dist/common/fileDetector.js:114:33)
2024-06-28 11:55:33.722 INFO 30633 [midway:bootstrap] exit with code:1

[md-vike.zip](https://github.com/user-attachments/files/16023949/md-vike.zip)

**Comment by brillout** [comment]
What's the failing `assert()` line? It should be at the third line of the stack trace (`file:///md-vike/dist/client/assets/entries/entry-client-routing.D3rq4nRt.js:3:26982`).

**Comment by amumufun** [comment]
I found the cause of the problem, it has nothing to do with vike, thanks.

**Comment by brillout** [comment]
If you can still share the failing `assert()` line that'd be great, as Vike should in principle never throw a `[vike@0.4.177][Bug] You stumbled upon a Vike bug` but show a more helpful error message instead.
