### ISSUE TITLE
vike bug

### ISSUE THREAD

**Issue by sgusman** [vikejs/vike#1730]
### Description

Error: [vike@0.4.177][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at createErrorWithCleanStackTrace (createErrorWithCleanStackTrace.js:4:17)
    at assert (assert.js:54:27)
    at parseUrl (parseUrl.js:45:5)
    at getUrlParsed (getPageContextUrlComputed.js:61:12)
    at Object.urlPathnameGetter [as urlPathname] (getPageContextUrlComputed.js:64:26)
    at assertPageContextUrl (getPageContextUrlComputed.js:119:31)
    at route (index.js:18:5)
    at renderPageNominal (renderPageClientSide.js:74:46)
    at async renderPageClientSide (renderPageClientSide.js:31:5)
    at async navigate (navigate.js:16:5)

**Comment by brillout** [comment]
I'll re-open once I get more information.
