### ISSUE TITLE
Vike bug

### ISSUE THREAD

**Issue by max-debosscher** [vikejs/vike#1735]
### Description

error during build:
Error: [vike@0.4.177][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at file:///D:/Documents/Development/maximus-cms/client/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:134:13
    at Array.map (<anonymous>)
    at loadInterfaceFiles (file:///D:/Documents/Development/maximus-cms/client/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:130:23)
    at loadVikeConfig (file:///D:/Documents/Development/maximus-cms/client/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:236:40)
    at loadVikeConfig_withErrorHandling (file:///D:/Documents/Development/maximus-cms/client/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:198:15)
    at getVikeConfig (file:///D:/Documents/Development/maximus-cms/client/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:75:12) 
    at getConfigVikPromise (file:///D:/Documents/Development/maximus-cms/client/node_modules/vike/dist/esm/node/plugin/plugins/config/index.js:27:54)

**Comment by max-debosscher** [comment]
Thanks for responding, the problem was caused by me naming a folder "+null-module" in /src to have Vite redirect some imports. So it's already been fixed.

**Comment by brillout** [comment]
:+1: Btw. would your company be up for sponsoring (#1350)? Sponsors make a massive difference.
