### ISSUE TITLE
vike-react/config sets an unknown config Loading when use both `vike-react` and `vike-vue`

### ISSUE THREAD

**Issue by vitalybaev** [vikejs/vike#1812]
### Description

I'm not sure, that it's a bug, but looks strange to me.

I want to try both frameworks (React and Vue) in the single project, but on the different pages. From the documentation [it seems that it should work](https://vike.dev/config#powerful).

But when I made minimal setup with both framework, running `pnpm dev` I get:

```
> test-vike-vue-with-react@0.0.1 dev /home/vitalybaev/test-vike-vue-with-react
> vite

Error: [vike][Wrong Usage] vike-react/config sets an unknown config Loading
    at handleUnknownConfig (file:///home/vitalybaev/test-vike-vue-with-react/node_modules/.pnpm/vike@0.4.184_vite@5.4.1/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:893:15)
    at assertConfigExists (file:///home/vitalybaev/test-vike-vue-with-react/node_modules/.pnpm/vike@0.4.184_vite@5.4.1/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:1003:5)
    at getConfigDefinition (file:///home/vitalybaev/test-vike-vue-with-react/node_modules/.pnpm/vike@0.4.184_vite@5.4.1/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:980:5)
    at eval (file:///home/vitalybaev/test-vike-vue-with-react/node_modules/.pnpm/vike@0.4.184_vite@5.4.1/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:326:31)
    at Array.forEach (<anonymous>)
    at eval (file:///home/vitalybaev/test-vike-vue-with-react/node_modules/.pnpm/vike@0.4.184_vite@5.4.1/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:323:21)
    at Array.forEach (<anonymous>)
    at assertUsageGlobalConfigs (file:///home/vitalybaev/test-vike-vue-with-react/node_modules/.pnpm/vike@0.4.184_vite@5.4.1/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:315:32)
 ELIFECYCLE  Command failed with exit code 1.
```

## Source Code

* [Open StackBlitz](https://stackblitz.com/~/github.com/vitalybaev/test-vike-vue-with-react)
* [GitHub Repo](https://github.com/vitalybaev/test-vike-vue-with-react)

## Additional information
* `vike` 0.4.184
* `vike-react` 0.5.2
* `vike-vue` 0.8.1

I scaffolded both projects with Bati:
```
pnpm create bati --react --tailwindcss --biome
pnpm create bati --vue --tailwindcss --biome
```

then I removed all unnecessary parts, like data fetching or todo page, created two route groups `(react)` and `(vue)` where placed respecting configuration.

**Comment by brillout** [comment]
Closing in favor of https://github.com/vikejs/vike/issues/1813.
