### ISSUE TITLE
Build fails for virtual files?

### ISSUE THREAD

**Issue by magne4000** [vikejs/vike#1816]
```
[vike@0.4.187][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at assertPathFilesystemAbsolute (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.187_react-streaming@0.3.43_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.4.1/node_modules/vike/dist/esm/utils/assertPathFilesystemAbsolute.js:13:5)
    at assertModuleId (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.187_react-streaming@0.3.43_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.4.1/node_modules/vike/dist/esm/node/plugin/shared/getFilePath.js:133:5)
    at getModuleFilePath (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.187_react-streaming@0.3.43_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.4.1/node_modules/vike/dist/esm/node/plugin/shared/getFilePath.js:120:5)
    at getModuleFilePathAbsolute (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.187_react-streaming@0.3.43_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.4.1/node_modules/vike/dist/esm/node/plugin/shared/getFilePath.js:111:73)
    at rollupOutput.manualChunks (file:///tmp/bati-app/node_modules/.pnpm/vike@0.4.187_react-streaming@0.3.43_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@5.4.1/node_modules/vike/dist/esm/node/plugin/plugins/distFileNames.js:51:46)
    at Bundle.assignManualChunks (file:///tmp/bati-app/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:18317:42)
    at Bundle.generateChunks (file:///tmp/bati-app/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:18349:20)
    at Bundle.generate (file:///tmp/bati-app/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:18268:39)
    at file:///tmp/bati-app/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20832:27
    at catchUnfinishedHookActions (file:///tmp/bati-app/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20258:16)
    at build (file:///tmp/bati-app/node_modules/.pnpm/vite@5.4.1/node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:65331:16)
    at CAC.<anonymous> (file:///tmp/bati-app/node_modules/.pnpm/vite@5.4.1/node_modules/vite/dist/node/cli.js:828:5)
 ELIFECYCLE  Command failed with exit code 1.
```

```shell
pnpm create bati --react --compiled-css --eslint
cd my-app
pnpm i
pnpm run build
```

Adding some debug in the first file mentioned in the log shows that the assert fails for the file `virtual:vite-plugin-compiled-react:41e0b51.css`

**Comment by brillout** [comment]
Fix released in `0.4.188`.
