### ISSUE TITLE
Build error starting from 0.4.187 

### ISSUE THREAD

**Issue by ktdd** [vikejs/vike#1818]
### Description

```
[vike@0.4.189][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at isFilePathAbsoluteFilesystem (file:///A:/[REDACTED]/node_modules/vike/dist/esm/utils/isFilePathAbsoluteFilesystem.js:38:13)
    at assertFilePathAbsoluteFilesystem (file:///A:/[REDACTED]/node_modules/vike/dist/esm/utils/isFilePathAbsoluteFilesystem.js:16:12)
    at assertModuleId (file:///A:/[REDACTED]/node_modules/vike/dist/esm/node/plugin/shared/getFilePath.js:133:5)
    at rollupOutput.manualChunks (file:///A:/[REDACTED]/node_modules/vike/dist/esm/node/plugin/plugins/distFileNames.js:53:33)
    at Bundle.assignManualChunks (file:///A:/[REDACTED]/node_modules/rollup/dist/es/shared/node-entry.js:18154:42)
    at Bundle.generateChunks (file:///A:/[REDACTED]/node_modules/rollup/dist/es/shared/node-entry.js:18186:20)
    at Bundle.generate (file:///A:/[REDACTED]/node_modules/rollup/dist/es/shared/node-entry.js:18105:39)
    at file:///A:/[REDACTED]/node_modules/rollup/dist/es/shared/node-entry.js:20661:27
```

Build is working fine in 0.4.186. Windows 11, TS React project. Let me know if I can provide additional info.

**Comment by brillout** [comment]
Insert the following before line `37` at `node_modules/vike/dist/esm/utils/isFilePathAbsoluteFilesystem.js` and report back the logs.

```diff
        // Ensure isFilePathAbsoluteFilesystem() returns `false` if path is absolute starting from the user root dir (see comments above).
+       console.log('stack', (new Error()).stack);
+       console.log('filePath', filePath);
        if (yes)
            assert(!filePath.startsWith('/'));
        return yes;

```

**Comment by ktdd** [comment]
[stack.txt](https://github.com/user-attachments/files/16674014/stack.txt)

**Comment by brillout** [comment]
[Fix](https://github.com/vikejs/vike/commit/6dfac95352edc476981bfae9461f2af660702c53) pre-released as `0.4.189-commit-6dfac95`, can you confirm it works?

**Comment by ktdd** [comment]
Build runs successfully now, so it seems to be fixed! I'll let you know if I run into problems. Thanks!

**Comment by brillout** [comment]
:+1: Btw. in case your company is up for it we're looking for sponsors (#1350). It makes a massive difference to us!

**Comment by ktdd** [comment]
> 👍 Btw. in case your company is up for it we're looking for sponsors (#1350). It makes a massive difference to us!

I develop (volunteer) software for a non-profit so that they can pinch every penny so unfortunately sponsoring isn't possible. Anyway, I've been using Vike since the early VPS days in my personal projects so I sent at least a little something your way. Keep up the excellent work.

**Comment by brillout** [comment]
Thank you @ktdd, I appreciate it :green_heart:
