### ISSUE TITLE
I stumbled upon a Vike bug.

### ISSUE THREAD

**Issue by mean-ui-thread** [vikejs/vike#1828]
### Description

```
3:54:32 p.m. [vike@0.4.193][request(2)][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at assertPlusFileExport (file:///home/mean-ui-thread/git/vike-test/node_modules/vike/dist/esm/shared/page-configs/assertPlusFileExport.js:30:5)
    at parseValueSerialized (file:///home/mean-ui-thread/git/vike-test/node_modules/vike/dist/esm/shared/page-configs/serialize/parsePageConfigs.js:107:9)
    at file:///home/mean-ui-thread/git/vike-test/node_modules/vike/dist/esm/shared/page-configs/serialize/parsePageConfigs.js:59:48
    at Array.map (<anonymous>)
    at file:///home/mean-ui-thread/git/vike-test/node_modules/vike/dist/esm/shared/page-configs/serialize/parsePageConfigs.js:58:43
    at Array.forEach (<anonymous>)
    at parseConfigValuesSerialized_tmp (file:///home/mean-ui-thread/git/vike-test/node_modules/vike/dist/esm/shared/page-configs/serialize/parsePageConfigs.js:54:44)
    at parseConfigValuesSerialized (file:///home/mean-ui-thread/git/vike-test/node_modules/vike/dist/esm/shared/page-configs/serialize/parsePageConfigs.js:8:26)
3:54:32 p.m. [vike][request(2)] HTTP response / ERR
```

**Comment by mean-ui-thread** [comment]
I think the issue was actually on my side. I forgot to add `export default` in front of `function Head() {` in my `+Head.tsx` file. I still raised the issue just in case it means something else :shrug:
