### ISSUE TITLE
examples/i18n is not buildable

### ISSUE THREAD

**Issue by AoSankaku** [vikejs/vike#1863]
### Description

An example in examples/i18n is not buildable.

`npm run build` returns:

```
> build
> vite build

vite v5.4.3 building for production...
✓ 182 modules transformed.
dist/client/_temp_manifest.json                                    2.31 kB │ gzip:  0.46 kB
dist/client/assets/static/renderer_Layout-031b266d.Cqz1SQAi.css    0.11 kB │ gzip:  0.11 kB
dist/client/assets/chunks/chunk-Bh9oUNAu.js                        0.06 kB │ gzip:  0.08 kB
dist/client/assets/entries/pages_about.OKHrJ5GZ.js                 1.31 kB │ gzip:  0.51 kB
dist/client/assets/entries/pages_movies.D7Xa3L-2.js                1.43 kB │ gzip:  0.57 kB
dist/client/assets/entries/pages_index.yzWykeJh.js                 1.81 kB │ gzip:  0.70 kB
dist/client/assets/entries/entry-client-routing.Ckb3HvbX.js       72.09 kB │ gzip: 23.30 kB
dist/client/assets/chunks/chunk-ClEYa4BI.js                      144.60 kB │ gzip: 46.70 kB
vite v5.4.3 building SSR bundle for production...
✓ 5 modules transformed.
x Build failed in 27ms
[vite]: Rollup failed to resolve import "node-fetch" from "C:/Users/abcde/dev/web/react/vike/examples/i18n/pages/movies/+onBeforeRender.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/Users/abcde/dev/web/react/vike/examples/i18n/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65511:17)
    at onwarn (file:///C:/Users/abcde/dev/web/react/vike/examples/i18n/node_modules/@vitejs/plugin-react/dist/index.mjs:266:9)
    at config.build.rollupOptions.onwarn (file:///C:/Users/abcde/dev/web/react/vike/examples/i18n/node_modules/vike/dist/esm/node/plugin/plugins/suppressRollupWarning.js:20:36)
    at onRollupWarning (file:///C:/Users/abcde/dev/web/react/vike/examples/i18n/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65541:5)
    at onwarn (file:///C:/Users/abcde/dev/web/react/vike/examples/i18n/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65206:7)
    at file:///C:/Users/abcde/dev/web/react/vike/examples/i18n/node_modules/rollup/dist/es/shared/node-entry.js:18668:13
    at Object.logger [as onLog] (file:///C:/Users/abcde/dev/web/react/vike/examples/i18n/node_modules/rollup/dist/es/shared/node-entry.js:20306:9)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/abcde/dev/web/react/vike/examples/i18n/node_modules/rollup/dist/es/shared/node-entry.js:19257:26)
    at file:///C:/Users/abcde/dev/web/react/vike/examples/i18n/node_modules/rollup/dist/es/shared/node-entry.js:19215:26 {
  watchFiles: [
    'C:/Users/abcde/dev/web/react/vike/examples/i18n/renderer/+onRenderHtml.jsx',
    'C:/Users/abcde/dev/web/react/vike/examples/i18n/pages/movies/+Page.jsx',
    'C:/Users/abcde/dev/web/react/vike/examples/i18n/pages/about/+Page.jsx',
    'C:/Users/abcde/dev/web/react/vike/examples/i18n/pages/movies/+onBeforeRender.js',
    'C:/Users/abcde/dev/web/react/vike/examples/i18n/pages/index/+Page.jsx',
    'C:\\Users\\abcde\\dev\\web\\react\\vike\\examples\\i18n\\package.json',
    'C:\\Users\\abcde\\dev\\web\\react\\vike\\package.json'
  ]
}
```

**Comment by brillout** [comment]
It builds just fine on my side. I suspect you made some problematic changes, but minimal reproduction welcome if you believe otherwise and I'll re-open.

**Comment by AoSankaku** [comment]
Sorry but I've made literally no changes on my side (because it may be problematic as you mentioned). I just did:

1. Clone the repo
2. npm install
3. npm run dev(successfully worked but movies is broken)
4. npm run build→above error
