### ISSUE TITLE
Azure build - POSIX path

### ISSUE THREAD

**Issue by lvaoliveira** [vikejs/vike#1935]
### Description

file: C:\a\4\s\src\entry-client.tsx
    at assertPosixPath (file:///C:/a/4/s/node_modules/vike/dist/esm/utils/filesystemPathHandling.js:15:5)
    at Object.transform (file:///C:/a/4/s/node_modules/vike/dist/esm/node/plugin/plugins/envVars.js:28:13)
    at file:///C:/a/4/s/node_modules/rollup/dist/es/shared/node-entry.js:20730:40

**Comment by brillout** [comment]
Can you share the error message?

**Comment by brillout** [comment]
Nevermind, I see what's going on.

**Comment by brillout** [comment]
Fix pre-released as `0.4.199-commit-749c7bd`.

**Comment by lvaoliveira** [comment]
Thank you so much for the quick reaction on the fix.. AWESOME!!!
