### ISSUE TITLE
Bug during build

### ISSUE THREAD

**Issue by Areg472** [vikejs/vike#1956]
### Description

error during build:
[vite-plugin-vercel] [vike@0.4.200][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at getGlobalContext (file:///C:/Users/User/WebstormProjects/ocean-plus-react/node_modules/vike/dist/esm/node/runtime/globalContext.js:32:5)
    at getRenderContext (file:///C:/Users/User/WebstormProjects/ocean-plus-react/node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js:165:27)     
    at getPagesAndRoutes (file:///C:/Users/User/WebstormProjects/ocean-plus-react/node_modules/vike/dist/esm/__internal/index.js:18:33)
    at _getPagesWithConfigs (file:///C:/Users/User/WebstormProjects/ocean-plus-react/node_modules/@vite-plugin-vercel/vike/dist/vike.js:275:77)
    at getPagesWithConfigs (file:///C:/Users/User/WebstormProjects/ocean-plus-react/node_modules/@vite-plugin-vercel/vike/dist/vike.js:271:21)
    at vercel.additionalEndpoints (file:///C:/Users/User/WebstormProjects/ocean-plus-react/node_modules/@vite-plugin-vercel/vike/dist/vike.js:367:46)
    at getAdditionalEndpoints (file:///C:/Users/User/WebstormProjects/ocean-plus-react/node_modules/vite-plugin-vercel/dist/index.js:94:27)
    at getEntries (file:///C:/Users/User/WebstormProjects/ocean-plus-react/node_modules/vite-plugin-vercel/dist/index.js:131:11)

**Comment by brillout** [comment]
Closing in favor of https://github.com/magne4000/vite-plugin-vercel/issues/122.
