### ISSUE TITLE
Found this in my console

### ISSUE THREAD

**Issue by dapinitial** [vikejs/vike#1991]
### Description

Uncaught Error: [vike@0.4.204][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at createErrorWithCleanStackTrace (createErrorWithCleanStackTrace.js:4:17)
    at assert (assert.js:54:27)
    at isSamePageHashLink (skipLink.js:40:5)
    at skipLink (skipLink.js:12:9)
    at addLinkPrefetchHandlers_apply (prefetch.js:173:13)

**Comment by brillout** [comment]
I believe it's fixed in 205. I'll re-open if you still get this with 205.
