### ISSUE TITLE
[@brillout/vite-plugin-server-entry] Cannot find server entry

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike#2010]
### Description

After `yarn build` and `yarn serve`, I get `Cannot find server entry`.

### Repro (repo: [template-vike-solid-daisyui-hono](https://github.com/templates-ecosystem/template-vike-solid-daisyui-hono) ~ branch: [issue-vike-2010](https://github.com/templates-ecosystem/template-vike-solid-daisyui-hono/tree/issue-vike-2010))
- `git clone https://github.com/templates-ecosystem/template-vike-solid-daisyui-hono.git`
- `git checkout issue-vike-2010`
- `cd template-vike-solid-daisyui-hono`
- `yarn`
- `yarn build`
  ```console
  vite v5.4.11 building for production...
  
  (!) outDir C:\template-vike-solid-daisyui-hono\.vite\dist\client is not inside project root and will not be emptied.
  Use --emptyOutDir to override.
  
  ✓ 83 modules transformed.
  ../.vite/dist/client/_temp_manifest.json                               0.92 kB │ gzip:  0.35 kB
  ../.vite/dist/client/assets/entries/pages_index.D328U0lo.js            0.74 kB │ gzip:  0.37 kB
  ../.vite/dist/client/assets/entries/entry-server-routing.BbDBASk5.js  31.50 kB │ gzip: 11.30 kB
  vite v5.4.11 building SSR bundle for production...
  
  (!) outDir C:\template-vike-solid-daisyui-hono\.vite\dist\server is not inside project root and will not be emptied.
  Use --emptyOutDir to override.
  
  ✓ 5 modules transformed.
  ../.vite/dist/server/package.json             0.02 kB
  ../.vite/dist/server/_temp_manifest.json      0.48 kB
  ../.vite/dist/server/entries/pages_index.mjs  0.78 kB
  ../.vite/dist/server/index.mjs                2.77 kB
  ✓ built in 43ms
  ✓ built in 831ms
  ```
- `yarn serve`
- go to `http://localhost:3000`
- Output (browser): `An error occurred.`
- Output (server):
  ```console
    ➜  Local:   http://localhost:3000/
    ➜  Network: use --host to expose
    ➜  press h + enter to show help
  11:00:21 [vike][request(1)] HTTP request: /
  11:00:21 [vike][request(1)][Error] An error was thrown:
  Error: [@brillout/vite-plugin-server-entry@0.5.1][Wrong Usage] Cannot find server entry. If you use rollupOptions.output.entryFileNames then make sure to not rename the server entry file. Make sure that one of the following exists:
    entry.mjs
    entry.js
    entry.cjs
    entryOthers.mjs
    entryOthers.js
    entryOthers.cjs
      at crawlServerEntry (C:\Users\<USER>\AppData\Local\Yarn\Berry\cache\@brillout-vite-plugin-server-entry-npm-0.5.1-c5b56633a1-10c0.zip\node_modules\@brillout\vite-plugin-server-entry\dist\runtime\crawlServerEntry.js:67:29)
      at importServerProductionEntry (C:\Users\<USER>\AppData\Local\Yarn\Berry\cache\@brillout-vite-plugin-server-entry-npm-0.5.1-c5b56633a1-10c0.zip\node_modules\@brillout\vite-plugin-server-entry\dist\runtime\importServerProductionEntry.js:34:19)
      at loadImportBuild (file:///C:/template-vike-solid-daisyui-hono/.yarn/__virtual__/vike-virtual-3abe11c81b/4/Users/<USER>/AppData/Local/Yarn/Berry/cache/vike-npm-0.4.206-5dcbd8efc2-10c0.zip/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:9)
      at initGlobalContext (file:///C:/template-vike-solid-daisyui-hono/.yarn/__virtual__/vike-virtual-3abe11c81b/4/Users/<USER>/AppData/Local/Yarn/Berry/cache/vike-npm-0.4.206-5dcbd8efc2-10c0.zip/node_modules/vike/dist/esm/node/runtime/globalContext.js:165:30)
      at initGlobalContext_renderPage (file:///C:/template-vike-solid-daisyui-hono/.yarn/__virtual__/vike-virtual-3abe11c81b/4/Users/<USER>/AppData/Local/Yarn/Berry/cache/vike-npm-0.4.206-5dcbd8efc2-10c0.zip/node_modules/vike/dist/esm/node/runtime/globalContext.js:105:5)
      at renderPageAndPrepare (file:///C:/template-vike-solid-daisyui-hono/.yarn/__virtual__/vike-virtual-3abe11c81b/4/Users/<USER>/AppData/Local/Yarn/Berry/cache/vike-npm-0.4.206-5dcbd8efc2-10c0.zip/node_modules/vike/dist/esm/node/runtime/renderPage.js:65:9)
      at file:///C:/template-vike-solid-daisyui-hono/.yarn/__virtual__/vike-virtual-3abe11c81b/4/Users/<USER>/AppData/Local/Yarn/Berry/cache/vike-npm-0.4.206-5dcbd8efc2-10c0.zip/node_modules/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:54:35
      at renderPage (file:///C:/template-vike-solid-daisyui-hono/.yarn/__virtual__/vike-virtual-3abe11c81b/4/Users/<USER>/AppData/Local/Yarn/Berry/cache/vike-npm-0.4.206-5dcbd8efc2-10c0.zip/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:35)
  ```

`@brillout/vite-plugin-server-entry` maybe try to search `./.vite/dist/server/entry.mjs` instead of `./.vite/dist/server/index.mjs`

Other relevant infos for warnings in build step:
```console
(!) outDir C:\template-vike-solid-daisyui-hono\.vite\dist\client is not inside project root and will not be emptied.
Use --emptyOutDir to override.

(!) outDir C:\template-vike-solid-daisyui-hono\.vite\dist\server is not inside project root and will not be emptied.
Use --emptyOutDir to override.
```

**Comment by brillout** [comment]
Can you publish a reproduction that is minimal? I'll re-open then.

**Comment by rtritto** [comment]
@brillout done, new minimal repro on branch [issue-vike-2010](https://github.com/templates-ecosystem/template-vike-solid-daisyui-hono/tree/issue-vike-2010)

**Comment by rtritto** [comment]
First comment updated with the minimal repro.
@brillout please, can you reopen?

**Comment by brillout** [comment]
Don't pressure please. I'm on it.

**Comment by rtritto** [comment]
Sorry, it wasn't intentional, I didn't find any feedback

**Comment by brillout** [comment]
I could reproduce. I'll have a look at it later today/tomorrow.

**Comment by brillout** [comment]
[Fixed](https://github.com/vikejs/vike-node/commit/2fa784e8f14e57a8b765f2e068faf784e8a11330).
