### ISSUE TITLE
Error: [vike@0.4.194][Bug] You stumbled upon a Vike bug.

### ISSUE THREAD

**Issue by mango-tree** [vikejs/vike#2011]
### Description

Hi, I got the error when I deploy service. Can you check the reason? I got this log, but the site is working well.
```
    "react-streaming": "^0.3.43",
    "vike": "^0.4.194",
    "vite": "^5.4.1",
```

```
Error: [vike@0.4.194][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at renderDocumentHtml (file:///app/node_modules/.pnpm/vike@0.4.194_react-streaming@0.3.43_react-dom@18.2.0_react@18.2.0__react@18.2.0__vite@5.4.1_@_or3fmpotentxbaacmx4zfputhq/node_modules/vike/dist/esm/node/runtime/html/renderHtml.js:52:5)
    at executeOnRenderHtmlHook (file:///app/node_modules/.pnpm/vike@0.4.194_react-streaming@0.3.43_react-dom@18.2.0_react@18.2.0__react@18.2.0__vite@5.4.1_@_or3fmpotentxbaacmx4zfputhq/node_modules/vike/dist/esm/node/runtime/renderPage/executeOnRenderHtmlHook.js:30:30)
    at async renderPageAlreadyRouted (file:///app/node_modules/.pnpm/vike@0.4.194_react-streaming@0.3.43_react-dom@18.2.0_react@18.2.0__react@18.2.0__vite@5.4.1_@_or3fmpotentxbaacmx4zfputhq/node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js:58:30)
    at async renderPageNominal (file:///app/node_modules/.pnpm/vike@0.4.194_react-streaming@0.3.43_react-dom@18.2.0_react@18.2.0__react@18.2.0__vite@5.4.1_@_or3fmpotentxbaacmx4zfputhq/node_modules/vike/dist/esm/node/runtime/renderPage.js:282:36)
    at async renderPageAlreadyPrepared (file:///app/node_modules/.pnpm/vike@0.4.194_react-streaming@0.3.43_react-dom@18.2.0_react@18.2.0__react@18.2.0__vite@5.4.1_@_or3fmpotentxbaacmx4zfputhq/node_modules/vike/dist/esm/node/runtime/renderPage.js:116:45)
    at async renderPageAndPrepare (file:///app/node_modules/.pnpm/vike@0.4.194_react-streaming@0.3.43_react-dom@18.2.0_react@18.2.0__react@18.2.0__vite@5.4.1_@_or3fmpotentxbaacmx4zfputhq/node_modules/vike/dist/esm/node/runtime/renderPage.js:96:12)
    at async renderPage_wrapper (file:///app/node_modules/.pnpm/vike@0.4.194_react-streaming@0.3.43_react-dom@18.2.0_react@18.2.0__react@18.2.0__vite@5.4.1_@_or3fmpotentxbaacmx4zfputhq/node_modules/vike/dist/esm/node/runtime/renderPage.js:25:24)
```

**Comment by brillout** [comment]
Update to the latest version then add the following before the line `52` of `node_modules/vike/dist/esm/node/runtime/html/renderHtml.js`.

```diff
+   console.log('documentHtml', documentHtml);
    assert(false);
```

Report back the log.

**Comment by mango-tree** [comment]
I found that it caused by our business logic. Sorry to bother.

**Comment by brillout** [comment]
No worries. The error should be improved regardless. If you can [provide this](https://github.com/vikejs/vike/issues/2011#issuecomment-2527269336) that would be great.

**Comment by brillout** [comment]
I found the issue, the error message will now be helpful starting from `0.4.209`.
