### ISSUE TITLE
Dependency issues for dev and build

### ISSUE THREAD

**Issue by jscottsf** [vikejs/vike#2016]
### Description

Updated to Vike 0.4.207.

When I run `npm run dev` I now get

```
file:///Users/zzzzz/Repos/zzz-web-site/node_modules/vike/dist/esm/node/runtime/html/serializePageContextClientSide.js:3
import { stringify, isJsonSerializerError } from '@brillout/json-serializer/stringify';
                    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'isJsonSerializerError' not found. The requested module '@brillout/json-serializer/stringify' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@brillout/json-serializer/stringify';
const { stringify, isJsonSerializerError } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.1
```

When I run 'npm run build` I now get

```
failed to load config from /Users/zzzzz/Repos/zzz-web-site/vite.config.js
error during build:
file:///Users/zzzzz/Repos/zzz-web-site/node_modules/vike/dist/esm/shared/page-configs/serialize/parsePageConfigs.js:5
import { parseTransform } from '@brillout/json-serializer/parse';
         ^^^^^^^^^^^^^^
SyntaxError: Named export 'parseTransform' not found. The requested module '@brillout/json-serializer/parse' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@brillout/json-serializer/parse';
const { parseTransform } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadConfigFromBundledFile (file:///Users/zzzzz/Repos/zzz-web-site/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66691:15)
    at async loadConfigFromFile (file:///Users/zzzzz/Repos/zzz-web-site/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66532:24)
    at async resolveConfig (file:///Users/zzzzz/Repos/zzz-web-site/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66140:24)
    at async build (file:///Users/zzzzz/Repos/zzz-web-site/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65237:18)
    at async CAC.<anonymous> (file:///Users/zzzzz/Repos/zzz-web-site/node_modules/vite/dist/node/cli.js:828:5)
```

**Comment by brillout** [comment]
Fix released in `0.4.208`.
