### ISSUE TITLE
Bug on upgrade to v1 and latest vike

### ISSUE THREAD

**Issue by Lxstr** [vikejs/vike#2018]
### Description

See: [https://github.com/Lxstr/autofeather-landing-vike](https://github.com/Lxstr/autofeather-landing-vike)

Task dev vite
error when starting dev server:
Error: [vike@0.4.208][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at isDev3 (/Users/user/Dev/autofeather-landing-vike/node_modules/.deno/vike@0.4.208/node_modules/vike/dist/esm/utils/isDev.js:12:5)
    at handler (/Users/user/Dev/autofeather-landing-vike/node_modules/.deno/vike@0.4.208/node_modules/vike/dist/esm/node/plugin/plugins/setGlobalContext.js:16:31)
    at runConfigHook (/Users/user/Dev/autofeather-landing-vike/node_modules/.deno/vite@4.5.5/node_modules/vite/dist/node/chunks/dep-b2890f90.js:66378:31)
    at resolveConfig (/Users/user/Dev/autofeather-landing-vike/node_modules/.deno/vite@4.5.5/node_modules/vite/dist/node/chunks/dep-b2890f90.js:65819:14)
    at _createServer (/Users/user/Dev/autofeather-landing-vike/node_modules/.deno/vite@4.5.5/node_modules/vite/dist/node/chunks/dep-b2890f90.js:65055:20)
    at CAC.<anonymous> (/Users/user/Dev/autofeather-landing-vike/node_modules/.deno/vite@4.5.5/node_modules/vite/dist/node/cli.js:763:24)

Adding the console log in node modules adds nothing new

**Comment by Lxstr** [comment]
I needed to upgrade to latest vite

**Comment by brillout** [comment]
What was the issue / how did you solve it?
