### ISSUE TITLE
Importing from vike/server throws error, missing /dist/esm/node/runtime/index.mjs

### ISSUE THREAD

**Issue by flipswitchingmonkey** [vikejs/vike#2040]
### Description

I'm importing vike's renderPage and bundle it through rollup. This works fine if I import like so:

```
import { renderPage } from 'vike'
```

However this is deprecated and outputs the notification that imports should be done from 
```
import { renderPage } from 'vike/server'
```

This, however, ends up with this error:
```
✖ Failed
[RollupError] Could not resolve "./dist/esm/node/runtime/index.mjs" from "node_modules/.pnpm/vike@0.4.211_vite@6.0.6_@types+node@22.10.2_terser@5.37.0_/node_modules/vike/server.js"

/Users/michael/dev/experiments/vike/node_modules/.pnpm/vike@0.4.211_vite@6.0.6_@types+node@22.10.2_terser@5.37.0_/node_modules/vike/server.js
RollupError: Could not resolve "./dist/esm/node/runtime/index.mjs" from "node_modules/.pnpm/vike@0.4.211_vite@6.0.6_@types+node@22.10.2_terser@5.37.0_/node_modules/vike/server.js"
    at error (file:///Users/michael/dev/experiments/vike/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/michael/dev/experiments/vike/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
    at file:///Users/michael/dev/experiments/vike/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
```

I wonder whether rollup may be part of the problem here, but looking at the actually imported package from `node_modules/vike/server.js`, it tries to import `./dist/esm/node/runtime/index.mjs` which does not exist

**Comment by brillout** [comment]
If you remove the file `node_modules/vike/server.js` does it work then?

**Comment by flipswitchingmonkey** [comment]
No, as expected it is then treated as an 'external dependency' sind the import is simply missing. If however I edit server.js to export from `index.js` instead of `index.mjs`, then it works.

**Comment by brillout** [comment]
It's defined over `package.json#exports`, so it should be working. I'm actually considering doing this: 5c0ce1dfcf76f41760fd6b4bca1c35dee4f4a2d3. Can you publish a reproduction?

**Comment by brillout** [comment]
I went ahead with the aforementioned patch (pre-released as `0.4.212-commit-1c62ff2`), but let me know if it doesn't work for you; I'm happy to revive those resolve fallbacks if I'm given a minimal reproduction.

**Comment by flipswitchingmonkey** [comment]
As before it works if I import from `vike` directly but now, since it is now removed, importing from `vike/server` will not work. Importing from `vike` still outputs the error, so presusambly this warning needs to be removed as well?

```
2025-01-06 08:29:41 Error: [vike][Warning] You have following imports which are outdated:
2025-01-06 08:29:41   import { something } from 'vike'
2025-01-06 08:29:41 Replace them with:
2025-01-06 08:29:41   import { something } from 'vike/server'
2025-01-06 08:29:41 Or if something is a type:
2025-01-06 08:29:41   import type { something } from 'vike/types'
2025-01-06 08:29:41 Make sure to import renderPage(), escapeInject, html, dangerouslySkipEscape(), pipeWebStream(), pipeNodeStream(), pipeStream(), stampPipe() from 'vike/server'. (Or inspect the error stack below to find the import causing this warning.)
```

**Comment by brillout** [comment]
> importing from `vike/server` will not work.

I'll need a minimal reproduction for that. (So that I can take the decision whether it's an issue with your build setup or whether Vike should revive those resolve fallbacks.)

**Comment by flipswitchingmonkey** [comment]
Here you go: https://github.com/flipswitchingmonkey/issue_vike_import

It's being imported in `src/frontend/index.ts` (ignore the sirv import, it makes no difference)

**Comment by brillout** [comment]
It does seem to be an issue about your build setup (I guess Directus's side). But I'll revive the resolve fallbacks nevertheless.

**Comment by brillout** [comment]
Pre-released as `0.4.212-commit-962127b`.
