### ISSUE TITLE
Error at `Object.pageFile.loadExportNames (/node_modules/vite-plugin-ssr\dist\cjs\shared\getPageFiles\parseGlobResults.js:39:36)`

### ISSUE THREAD

**Issue by DoloreMentale** [vikejs/vike#442]
### Description

Happens on yarn dev
package version: 0.4.31

### Error Stack

```shell
at Object.pageFile.loadExportNames (/node_modules/vite-plugin-ssr\dist\cjs\shared\getPageFiles\parseGlobResults.js:39:36)
at async /node_modules/vite-plugin-ssr\dist\cjs\shared\getPageFiles\analyzePageClientSide.js:40:9
at async Promise.all (index 1)
at async analyzePageClientSideInit (/node_modules/vite-plugin-ssr\dist\cjs\shared\getPageFiles\analyzePageClientSide.js:30:5)
at async Promise.all (index 1)
at async loadPageFilesServer (/node_modules/vite-plugin-ssr\dist\cjs\node\renderPage.js:364:69)
at async renderPageContext (/node_modules/vite-plugin-ssr\dist\cjs\node\renderPage.js:65:23)
at async renderPage (/node_modules/vite-plugin-ssr\dist\cjs\node\renderPage.js:151:16)
```

**Comment by brillout** [comment]
What is the entire error stack and error message?

**Comment by DoloreMentale** [comment]
> What is the entire error stack and error message?

There is only
Error: [vite-plugin-ssr@0.4.31][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/inv
ite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): /renderer/_default.page.client.js.

We previously had v. 0.4.17 and stumbled upon escapeInject error during the build, so we decided to update to latest version in case it is already fixed

```
Error: 'escapeInject' is not exported by node_modules/vite-plugin-ssr/dist/esm/client/node.js, imported by renderer/_default.page.server.js
    at error (/app/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/app/node_modules/rollup/dist/shared/rollup.js:12543:16)
    at Module.traceVariable (/app/node_modules/rollup/dist/shared/rollup.js:12902:29)
    at ModuleScope.findVariable (/app/node_modules/rollup/dist/shared/rollup.js:11554:39)
    at FunctionScope.findVariable (/app/node_modules/rollup/dist/shared/rollup.js:64[86](https://gitlab.com/a4572/alfabit-frontend/-/jobs/2992173152#L86):38)
    at ChildScope.findVariable (/app/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at Identifier.bind (/app/node_modules/rollup/dist/shared/rollup.js:7553:40)
    at TaggedTemplateExpression.bind (/app/node_modules/rollup/dist/shared/rollup.js:5383:23)
    at TaggedTemplateExpression.bind (/app/node_modules/rollup/dist/shared/rollup.js:11331:15)
    at VariableDeclarator.bind (/app/node_modules/rollup/dist/shared/rollup.js:5383:23)
    ```

**Comment by DoloreMentale** [comment]
@brillout is it okay that pageFilesClientSide (analyzePageClientSide.js) array of page files has different loadFile functions? 
```
const pageFilesClientSide = (0, getPageFilesClientSide_1.getPageFilesClientSide)(pageFilesAll, pageId);
```
only _default.page.client.js has loadExportNames, while all other pages have loadFile func?
```
{
     filePath: '/renderer/_default.page.client.js',
    fileType: '.page.client',
     isRelevant: [Function: isRelevant],
     isDefaultPageFile: true,
     isRendererPageFile: true,
     isErrorPageFile: false,
     pageId: '/renderer/_default',
     loadExportNames: [AsyncFunction (anonymous)]
}
```

**Comment by DoloreMentale** [comment]
@brillout is it okay that pageFilesClientSide (analyzePageClientSide.js) array of page files has different loadFile functions? 
```
const pageFilesClientSide = (0, getPageFilesClientSide_1.getPageFilesClientSide)(pageFilesAll, pageId);
```
only _default.page.client.js has loadExportNames, while all other pages have loadFile func?
```
{
     filePath: '/renderer/_default.page.client.js',
    fileType: '.page.client',
     isRelevant: [Function: isRelevant],
     isDefaultPageFile: true,
     isRendererPageFile: true,
     isErrorPageFile: false,
     pageId: '/renderer/_default',
     loadExportNames: [AsyncFunction (anonymous)]
}
```
